### ISSUE TITLE
Data tab should show new graphs

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#102]
See the collections on edrn-labcas.jpl.nasa.gov; we should show the 4 summary boxes and the 3 pie charts

**Comment by nutjob4life** [comment]
Question for @hoodriverheather:

On the page at https://edrn-labcas.jpl.nasa.gov/labcas-ui/a/index.html there are 4 boxes at the top, however one of those boxes is "# Favorited". See this screenshot:

![Screen Shot 2021-01-27 at 9 44 10 AM](https://user-images.githubusercontent.com/814813/106015703-5ac8f100-6084-11eb-9fe7-ef45b10fc3d4.png)

Reproducing the 4th box, "# Favorited" is going to be really tricky and will require modifications to LabCAS (the UI and the backend) as well as the portal; and the portal will need to check

1. Do I have a logged in user
2. If not, what to show here (or hide the box?)
3. If so, query LabCAS to find out what collections that user has "favorited" and show the matching number

I really question the utility of it. My feeling would be to skip it.

@dchrichto your thoughts?

**Comment by hoodriverheather** [comment]
@nutjob4life - sorry for confusion. Please ignore favorited. I agree - not necessary.
Thanks!
Heather

**Comment by nutjob4life** [comment]
To get stats on datasets and files into the portal I will need to also update the CancerDataExpo RDF generation to include that data; see EDRN/CancerDataExpo#12.

**Comment by nutjob4life** [comment]
Okay, the new approach is to embed a browser in the portal and have it retrieve the graphics from edrn-labcas, crop them, scale them, and put them on the page. Ugh. Plone is just awful sometimes 🤬
