### ISSUE TITLE
Protocols Graphics Updates (demo 2021-04-08)

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#123]
## 🤔 Tell Us About the Feature

During the EDRN Bioinformatics Meeting on 2021-04-08, participants had the following suggestions for the new `/data-and-resources/protocols` page:

- [x] Ensure a screen reader can handle the graphs (Section 508)
- [x] Provide a FAQ for search terms as the general public won't know what to type on the
- [x] Drop the green donut; the projects vs protocols distinction is not useful
- [x] Replace the green donut with cancer type (the "disease" relationship)
- [ ] Ensure that if you type a search term from any of the graphs that those matching results make sense

## 🗺 Context

The context is: the EDRN Bioinformatics Systems Planning Meeting held on 2021-04-08.

**Comment by nutjob4life** [comment]
@hoodriverheather 4 out of the 5 subtasks on this issue are done and I would like to demo it on the EDRN bioninformatics systems planning meeting on 2021-06-10. You can try it at https://edrn-dev.jpl.nasa.gov/portal/5/dev/data-and-resources/protocols too.

I will see about getting that 5th item done on 6-9 if possible.

**Comment by hoodriverheather** [comment]
@nutjob4life This is looking great! You should definitely show it on Thursday.
