### ISSUE TITLE
Improve navigation

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#127]
## 🤔 Tell Us About the Feature

Christos would like to see it easier to navigate protocols and other things:

> Sean and I chatted about the portal and navigation of the protocol data on the portal.  We can work to link faceted navigation and search together so they can work hand-in-hand and use the data in the protocols for classification/filtering while using text search to find keywords.  Adding pagination will help too since we are adding more and more protocols.

## 🎇 What Solution You'd Like

- [x] Pagination top and bottom
- [x] More facets on protocols
- [x] Maybe keyword search (?)

**Comment by nutjob4life** [comment]
@hoodriverheather two of these features are now live on the dev portal.

- There's pagination controls on the top and bottom of biomarkers, datasets, publications, and protocols pages
- On protocols, there's a PI facet at the bottom of the page; see it at https://edrn-dev.jpl.nasa.gov/portal/5/dev/data-and-resources/protocols

Christos's third request "a keyword search" I am having trouble comprehending. There's already a search box where you can type keywords.

Does he want something else? Checkboxes for keywords perhaps—and if so, what would those keywords be? What are the permissible values? Something like:

- [ ] Metabolomics
- [ ] Glycomics
- [ ] Proteomics
- [ ] Lung and Upper Aerodigestive Cancer Research Group
- [ ] Neoplasms of the bronchus & lung

The above mixes the field of research, collaborative group, and cancers studies vocabularies. Should those be three separate facets?

**Comment by hoodriverheather** [comment]
@nutjob4life I have been reading what Christos wrote in his email and looking at the Secure Site search and a few things come to mind:

- Do you have much control on where you put the search facets in Plone? Could they be on the left side next to the table?
- If you can, it might be nice to add facets to match the graphs. Field of Research, Collab Groups and Cancers studied
- If you add the additional facets it would allow a user to narrow down their search and also use the keyword search to do a combo type of search :)
- If that's too hard - maybe you could add these to the bottom of the page and we can update when we migrate from Plone?

Also - would be nice if the user can reset the search with a reset button.
 
We could have a quick call to discuss. I had to take that Thursday call from my car, so I don't have any notes.

**Comment by nutjob4life** [comment]
Thanks for the feedback @hoodriverheather. I'll see what's possible with Plone.

**Comment by hoodriverheather** [comment]
I think you could add a few facets and then see if Christos would like to add anything different. 
I'm not sure how much time you should spend on it. Maybe good to also ask Dan?

**Comment by nutjob4life** [comment]
@hoodriverheather all these changes will be available at https://edrn-dev.jpl.nasa.gov/portal/5/dev/data-and-resources/protocols on 6-18 once Jenkins makes a new build tonight—except for the Reset button.
