### ISSUE TITLE
Make LabCAS more obvious

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#146]
## 🤔 Tell Us About the Feature

Deanna and/or Jackie had some issues getting to [EDRN LabCAS](https://edrn-labcas.jpl.nasa.gov/) from the [EDRN Portal](https://edrn.nci.nih.gov/) and gave @hoodriverheather a "pop quiz" on doing it. They didn't realize you had to go to "Data" and instead came via "Informatics".

## 🎇 What Solution You'd Like

Not sure what the better approach should be; add comments to this ticket for discussion.

## 🗺 Context

EDRN Bioinformatics Status Meeting 2022-01-13.

**Comment by nutjob4life** [comment]
In the year since this ticket was filed, people are starting to figure out where LabCAS is. As a result, I'm closing this. But if this is still a challenge, feel free to re-open it.

**Comment by hoodriverheather** [comment]
Sounds good to me!
