### ISSUE TITLE
Report/export request

### ISSUE THREAD

**Issue by mryan4** [EDRN/P5#163]
Hi Sean,

1. Could you please run me a report with the following columns:
Biomarker ID
Biomarker HGNC Name
Biomarker Default Name
Description
Publications
Resources

This report is at the record level, i.e. BMDB says it contains 1416 biomarkers, so I would expect 1416 lines because I am not looking at any organ-level or protocol-level information.  (I guess there will be more than 1416 lines because of multiple publications and resources per record, but I think you know what I am getting at?)

2. Could you please run a second report that will be at the biomarker-organ-protocol level with the following columns:
Biomarker ID
Biomarker HGNC Name
Biomarker Default Name
Organ
Protocol ID
QA State that is on the Basics tab
QA State that is on the Organs tab but not associated with a specific protocol
Biomarker Phase that is on the Organs tab and is associated with a specific protocol

I know that this will have a lot of repeated information.  That's OK with me. 
I don't know which tables these fields are from, which is why I'm specifying exactly where in the BMDB UI I mean.
Please let me know if you have any questions/need clarification.

Thank you!

**Comment by nutjob4life** [comment]
Moved to BMDB repository as two separate issues:

- [Issue 51](https://github.com/EDRN/biomarker-database/issues/51)
- [Issue 52](https://github.com/EDRN/biomarker-database/issues/52)
