### ISSUE TITLE
Search descriptions ambiguous

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#167]
@dcrichto reported by email in `<D3219B64-E386-4A5B-B09C-09C0DD7E4717@jpl.nasa.gov>`:

> I did a search on CA125.  It shows a list of resources, including the biomarker ,but with no description.  When I click on CA125 as a biomarker, there is a description?  Are those functionally equivalent?

We need to disambiguate descriptions on search results.

**Comment by nutjob4life** [comment]
@hoodriverheather to test this, visit https://edrn-dev.jpl.nasa.gov/portal/renaissance/ and type

    ca125 "This gene encodes a protein that is a member of the mucin family"

into the search box and hit <kbd>Return</kbd>. On the matching item of type `Biomarker` with title `CA125`, there should be a description instead of the text `No description available`.

**Comment by hoodriverheather** [comment]
@nutjob4life Awesome - i see the description for ca125 when i search.
However, I don't see this biomarker show up in the search with Biomarker on the right side.

**Comment by hoodriverheather** [comment]
@nutjob4life The description for search seem ambiguous for items other than biomarkers. See the following:
<img width="1221" alt="Screen Shot 2023-01-12 at 2 09 54 PM" src="https://user-images.githubusercontent.com/58526347/212417126-cddf59da-8d61-41e1-ba00-5134a089fec1.png">

Screen Shot 2023-01-12 at 2 11 28 PM

Would it be possible to have description based on the content type?

person use their EDRN Title, if EDRN title is blank have some default text?
site use the Member Type, if blank - default text?
etc.
If this is possible, you could send me a list of content types and we could come up with a value to use and if blank what to use for default text.

**Comment by nutjob4life** [comment]
Closed as duplicated by several other issues, notably #219

**Comment by nutjob4life** [comment]
QC label missing but 6.0.2 frozen and shipped to NCI
