### ISSUE TITLE
Various 6.0.1 issues from Dan

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#169]
@dcrichto wrote in `<452B8C3F-C21D-493D-8273-C8216A530C06@jpl.nasa.gov>`:

1. The data categories have the same issues [as what?]
2. On the EDRN newsletter, is there a reason they aren’t chronological? https://edrn.nci.nih.gov/news-and-events/edrn-newsletter/
3. The CDE link goes to a 2016 version. Is that the latest and are these all the CDEs?
https://edrn.nci.nih.gov/data-and-resources/edrn-common-data-elements-cdes/
4. Why does the EDRN CDE link on the CDE page above link to a TCGA page?
5. Is the member finder in the drop down tabs?  I only see it on the home page.
6. When I go to the member finder and click on member A, it only shows Johns Hopkins, where are the others?
7. On the publications link and graphic, I would change the y access from amount to # of publications or something

**Comment by nutjob4life** [comment]
1. Fixed in #168.
2. Sorted on ops site into reverse-chronological order.
3. On that page there are 3 links; first gives a file `CDE_Export_for_Public_Portal_2021-04-21.xlsx`, the second goes to the "secure" site, the third gives a file `EDRNLabCASImagingCDEs.xlsx`. None of these seem to be from 2016.
4. I cannot find a link to TCGA on the page https://edrn.nci.nih.gov/data-and-resources/edrn-common-data-elements-cdes/
5. Because the Member Finder is a "view" and not a content page, I can't put it on the drop down menus. That why it's highlighted on the home page's boxes and on the sites page at https://edrn.nci.nih.gov/about-edrn/sites-rdf/ at the top.
6. In the RDF feed (as of 2022-12-01), there is only one "Associate Member A - EDRN Funded" site, and that's JHU.
7. Fixed in a3daa643c3c989b3507d43cf11bd06e13ca789f8

**Comment by nutjob4life** [comment]
@hoodriverheather to test this:

1. Notice there are legends on the Data Categories pie chart on https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/data/
2. Visit https://edrn.nci.nih.gov/news-and-events/edrn-newsletter/ and see reverse chronological order
3. Confirm there are no CDEs from 2016 on https://edrn.nci.nih.gov/data-and-resources/cde/
4. Confirm there is no link to TCGA on https://edrn.nci.nih.gov/data-and-resources/cde/
5. Nothing to test; can't be done
6. The SOAP API (which makes the RDF) has only one Associate Member A site at present.
7. Visit https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/publications/ and look at the left side of the chart: the word "Amount" has been replaced with "# Publications"

**Comment by hoodriverheather** [comment]
@nutjob4life this all looks good. :)

**Comment by nutjob4life** [comment]
I'm glad I can get _something_ right!
