### ISSUE TITLE
Cannot upload files bigger than 8kb

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#171]
In trying to edit content on the new Portal 6.0, we are finding some issues:

- We can add only small images to pages
- We can't post any `.xlsx` files (or .`pdf` files)
- We can post small text files, though
- We cannot edit pages with lots of text on them; only smaller pages

It appears the AWS WAF is blocking any `POST` payloads that exceed 8kb. We need the following request strings unblocked from the WAF:

- /admin/documents/
- /admin/images/
- /admin/pages/
- /admin/snippets/
- /django-admin/wagtaildocs/
- /django-admin/wagtailimages/

**Comment by nutjob4life** [comment]
See https://service.cancer.gov/ncisp?id=nci_ticket&sys_id=89e92ace1bd79550932da8efe54bcb6a&table=incident

**Comment by nutjob4life** [comment]
@hoodriverheather to test this, log onto the operational portal and try adding a large document or image—or try editing a page with a lot of text (https://edrn-dev.jpl.nasa.gov/portal/renaissance/about-edrn/mission-and-structure/ is a good candidate).

**Comment by hoodriverheather** [comment]
@nutjob4life I logged in, but know nothing about how to edit in Wagtail :)
Do I have permissions to edit? See screenshot - 
<img width="1096" alt="Screen Shot 2022-12-01 at 11 57 59 AM" src="https://user-images.githubusercontent.com/58526347/205147934-bc1a9186-a45c-412c-9248-c8efba232190.png">

**Comment by nutjob4life** [comment]
@hoodriverheather did you log in with your Informatics Center account or "secure" site account?

**Comment by hoodriverheather** [comment]
@nutjob4life I logged in using my kincaid username. It's the one that's in the "SuperUser" group.

**Comment by nutjob4life** [comment]
@hoodriverheather I see it in the logs, and I see it's even listed as "Administrator". Got time for a Slack huddle?

**Comment by hoodriverheather** [comment]
It works!!
