### ISSUE TITLE
Production Database Transfer for Wagtail

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#172]
For Plone, we had access to the `blobstorage` and `filestorage` for retrieving the production database for development purposes of each next version.
 
Wagtail doesn't use `blobstorage` or `filestorage`, though. It uses a `media` directory and PostgreSQL. We'll need a similar feature so we can continue to develop the EDRN portal. And this must be implemented on both sides, NCI and JPL.

I've submitted the following ticket to CBIIT to support the NCI side. This issue is to track the JPL side.

**Comment by nutjob4life** [comment]
Implemented in 78570151162f42370775766f8da7419fdb340993

**Comment by nutjob4life** [comment]
@hoodriverheather one way to test this is to add an image or document to the [production site](https://edrn.nci.nih.gov/), wait 24 hours, and then see if it shows up on the [dev site](https://edrn-dev.jpl.nasa.gov/portal/renaissance/).

Alternatively, you could make an edit to a page on production—wait 24 hours—and see if it appears on dev.

**Comment by hoodriverheather** [comment]
@nutjob4life Should I wait until the Wagtail training Monday? When I login to the Public Portal, I don't see any additional ways to edit the page. Am I missing something?

**Comment by nutjob4life** [comment]
@hoodriverheather yeah, something's not right! You got time for a huddle on Slack?

**Comment by nutjob4life** [comment]
@hoodriverheather to test this:

1. Visit https://edrn.nci.nih.gov/admin/ and log in with appropriate permissions
2. Click "Documents" on the left
3. Click "+ Add a document"
4. Drag in some file—any inoffensive file
5. Save it

Wait 25 hours. Then:

1. Visit https://edrn-dev.jpl.nasa.gov/portal/renaissance/admin/ with appropriate permissions
2. Click "Documents" on th left
3. See if your file from production has appeared on dev

**Comment by hoodriverheather** [comment]
@nutjob4life I just added the Lung Collaborative Group agenda to Documents using steps 1-5 above. I think this is a dumb question, but how do I actually link this on a page in the portal? I think it would be good to be able to link this to the Lung Collaborative Group call. 
Also, it seems the "event" i created for this yesterday doesn't exist today. Not sure if I'm doing something wrong.

**Comment by nutjob4life** [comment]
@hoodriverheather wow I almost lost this comment due to it being on a closed issue!

The steps to upload a document using steps 1–5 above are _not_ what people will do in practice. Those steps are just to test it.

> Also, it seems the "event" i created for this yesterday doesn't exist today

The nightly build starts off with a clean slate each time:

1. It erases the dev database
2. It copies the latest production database from edrn.nci.nih.gov
3. It then upgrades the database from 6.0.1 schema to 6.0.2 and adds all the new data (paperless, new reference sets, etc.)

So yes, events you created through-the-web are gone!
