### ISSUE TITLE
On the "Data" page, collab group names may be ambiguous

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#174]
The table of scientific data collections on the "Data" page on Portal 6 uses short names for collaborative groups, such as "Breast". This may be unclear because the group's name is "Breast and Gynecological Cancers Collaborative Research Group". While that name is painfully long, it does at least convey that it's cancers not just for the breast. Users may be unclear thinking they can't find gynecological cancers—but they can, they just have to select "breast".

Maybe call it "Breast/GYN".

(via @dcrichto)

**Comment by hoodriverheather** [comment]
@nutjob4life I agree that we can call it Breast/GYN. thanks!

**Comment by nutjob4life** [comment]
This is live now on the dev site: https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/data/

**Comment by nutjob4life** [comment]
@hoodriverheather this is live now on the dev site: This is live now on the dev site: https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/data/
