### ISSUE TITLE
"Paperless" import

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#179]
Import the remaining paperless documents from Plone.

- [x] Basic calendar events (title, body, zoom link, start time, time zone support)
- [x] A mix of RDF-sourced content and hand-editable content (😱), notably: description must be hand-editable (this mix makes things much more complicated)
- [x] Import of documents
- [x] Import of past events
- [x] Protection of certain groups with LDAP group controls
- [x] Link to groups page from Mission and Structure
- [x] Link to specific groups from paragraphs below diagram
- [x] Replace static site page with RDF-generated page

**Comment by hoodriverheather** [comment]
@nutjob4life I see the documents :)
When you edit this page in Wagtail (once it's live) will you also add the other features of the group pages? The tabs with the Documents and the Calendar at a minimum?

**Comment by nutjob4life** [comment]
I wasn't planning on adding Calendar features, just the documents.

The various collaborative groups and committees haven't used the calendar feature in quite some time. If they really want, we can simply create separate "folders" for events and documents.

**Comment by hoodriverheather** [comment]
I think we may need some of the older features for the "paperless". Jackie is doing training w sites and letting them know that's where they would go to get all info for a call. We should discuss.

**Comment by nutjob4life** [comment]
@hoodriverheather okay let's set up a time.

**Comment by nutjob4life** [comment]
Based on our meeting on 12-14 we need:
- [ ] Basic calendar events (title, body, zoom link, start time, time zone support)
- [ ] A mix of RDF-sourced content and hand-editable content (😱), notably: description must be hand-editable (this mix makes things much more complicated)
- [ ] Import of documents
- [ ] Import of past events
- [ ] Protection of certain groups with LDAP group controls

**Comment by hoodriverheather** [comment]
@nutjob4life is it easy to change the way the time displays when selecting a time to have it displayed in standard time vs 24 hr time?
I created a page. How do I attach a document?
https://edrn-dev.jpl.nasa.gov/portal/renaissance/about-edrn/mission-and-structure/groups/breast-and-gynecologic-cancers-research-group/edrn-lung-collaborative-group-call/
[Lung Collaborative Group Agenda Jan 2023.docx](https://github.com/EDRN/P5/files/10406998/Lung.Collaborative.Group.Agenda.Jan.2023.docx)

**Comment by hoodriverheather** [comment]
i created a new issue to track for next release to address comment above. https://github.com/EDRN/P5/issues/216

**Comment by nutjob4life** [comment]
@hoodriverheather no, the time display widget cannot be altered.

Attaching a document to a page: https://youtu.be/2WuEu2HQKh8
