### ISSUE TITLE
Weigh biomarkers more heavily in search results

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#185]
Just like the title says

**Comment by nutjob4life** [comment]
Solved by using Promoted Search Results

**Comment by hoodriverheather** [comment]
@nutjob4life this works for several of the biomarkers i searched for - love it!

Didn't work when searching MUC4, the biomarker was listed last on the 2nd page. Not sure why this one isn't working. 

See screen shot.
<img width="1328" alt="Screen Shot 2023-01-12 at 3 26 34 PM" src="https://user-images.githubusercontent.com/58526347/212202698-87aac185-2d41-4737-bd07-c2f2a7dfa0cc.png">

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this: https://edrn-dev.jpl.nasa.gov/portal/renaissance/search/?query=muc4

**Comment by hoodriverheather** [comment]
@nutjob4life looks great.

**Comment by nutjob4life** [comment]
![happy-dance](https://user-images.githubusercontent.com/814813/212504513-cd028495-9f45-4a0f-ba07-90e2554dc3ae.gif)
