### ISSUE TITLE
Diseases Studied legend has bug in data on dev

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#189]
## 🐛 Describe the Bug

on the protocol pagehttps://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/protocols/
[2:35](https://jpl.slack.com/archives/DSE5M4HCH/p1671489345950759)
graph Diseases Studied - legend is repeating the following disease multiple times:  Malignant ....lip, oral cavity... many times.
See attached screen shot - 
<img width="1212" alt="Screen Shot 2022-12-19 at 2 36 04 PM" src="https://user-images.githubusercontent.com/58526347/208542216-a0cf1fee-5b61-4893-b129-080021340341.png">

**Comment by nutjob4life** [comment]
@hoodriverheather I don't think this is a bug.

The "Disease" SOAP API from the DMCC produces _10 different diseases_ all labeled `Malignant neoplasms of lip, oral cavity and pharynx ` (with a trailing space) including these identifiers: `8`, `140`, `141`, `143`, `144`, `145`, `146`, `147`, `148`, `149`.

These are _distinct diseases_ as far as the DMCC is concerned, even if they all have the same label.

The "Protocols" SOAP API from the DMCC describes protocols using almost all of these disease identifers except №8:

-   When their SOAP API describes protocol 243, it says the cancer types are: `144, 143, 148, 140, 160, 147, 146, 149, 145, 141                                                    ` (complete with an incredible amount of trailing space).
-   When their SOAP API describes protocol 236, it says the cancer typs are: `144, 143, 148, 140, 160, 147, 146, 149, 145, 141                                                    ` (also with a lot of trailing space).

This data gets translated into RDF, ingested by the portal, populated in the database, and displayed in the legend.

I believe the DMCC should try to correct this.

**Comment by nutjob4life** [comment]
As mentioned during out 2022-12-20 staff meeting, we're going to turn off Diseases Studied for now.

**Comment by hoodriverheather** [comment]
+1
