### ISSUE TITLE
Convert RichText tables to TableBlock tables

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#198]
Although #173 enables table editing in Portal 6.0.2, existing tables such as on the [CLIA-approved markers page](https://edrn.nci.nih.gov/about-edrn/clia-approved-markers/) and the [FDA-approved tests page](https://edrn.nci.nih.gov/about-edrn/fda-approved-tests/) still aren't editable.

Yes, they could be re-created through-the-web as TableBlocks, but given that we have breathing room for the release of the next portal, we should go ahead and make conversion of those RichText `<table>`s into TableBlocks as part of the upgrade, as we understand that collaborators are champing at the bit to make changes to these tables, and if they have to wait for me to re-create them through-the-web, they may be somewhat forlorn.

**Comment by nutjob4life** [comment]
@hoodriverheather note that to this seems to work, but the table editor in Wagtail is really basic and is a step backwards from Plone. I think we'll want to discuss this further.

To test this:

1. Use Chrome on macOS—or use Chrome or Firefox on Windows
2. Visit https://edrn-dev.jpl.nasa.gov/portal/renaissance/ and click Log In
3. Click "I want to log in here"
4. Log in as a user in the Super User or Portal Content Custodians group
5. In the search box type `EDRN01` and hit return (enter)
6. Click the only matching hit, `EDRN01 — Total RNA Benchmarking Samples`
7. Click the NIH badge in the lower-right and choose "Edit this page"
8. Scroll to the second block, the "Table" block
9. Try editing the table and hit Publish; you can right-click in a cell to add rows and columns, remove rows and columns, etc.
10. Click "Publish" and "View Live" to see your changes

For all of Plone's warts, it had a better table editor. Here are the issues to discuss:

-   Browser support is limited
    -   On Windows, table editing works only with Chrome and Firefox
        -   Edge, the native Windows browser, does _not_ work
    -   On macOS, only Chrome works
        -   Firefox and Safari are out
-   Table cells may contain only _plain text_
    -   No formatting like bold, italic, strong, emphasis, etc.
    -   No hyperlinks!
        -   Visit https://edrn-dev.jpl.nasa.gov/portal/renaissance/about-edrn/clia-approved-markers/ and notice that all the links to biomarkers are gone
            -   They're just plain text now

This isn't even sufficient for the changes Jackie wants for the [Specimen Reference Sets](https://edrn.nci.nih.gov/data-and-resources/specimen-reference-sets/) page. She wants hyperlinks from within the table to the various sections below. But no hyperlinks within table cells are allowed here!

I'm thinking that I should leave in table editing support, but not convert pages like the CLIA, FDA, and Specimen Reference Sets to use it. Instead, maybe we should add support for a "Dangerous Raw HTML block" so we can at least write our own `<table>…</table>` HTML code to work around these glaring shortcomings.

**Comment by nutjob4life** [comment]
Found a better table editor, working on integrating it!

**Comment by nutjob4life** [comment]
Whew! OK. this is finally done and I'm glad you were on vacation during it because it literally took several days and a couple visits to the Wagtail Support Slack.

In addition to testing editing the "EDRN01 — Total RNA Benchmarking Samples" page (in the comment ↑), I've rewritten the [specimen reference sets page](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/specimen-reference-sets/) which uses the advanced table editor.

Try editing it and see if it works!

**Comment by hoodriverheather** [comment]
I can edit! Other improvements tracked in issue https://github.com/EDRN/P5/issues/203
