### ISSUE TITLE
Data quality reports

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#200]
In `<<0A17B6AF-912D-4D98-850F-B79D8FA43A95@jpl.nasa.gov>` , @dcrichto1 wrote:

> I am thinking we can write a piece of software that will run through and validate our data curation including
>
> - biomarkers that have no publications
> - biomarkers that have no datasets
> - datasets that have no identified EDRN PI
> - datasets that have no biomarkers
> - publications that have no EDRN PI

This issue tracks this feature request.

**Comment by nutjob4life** [comment]
@dcrichto1 take a peek at https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-quality/

Note: you'll need to log in as a member of the Super User group to access this. 

The idea: data quality linked to nightly ingest and we archive reports going back in time. I could add a chart that shows the number of data quality issues over time.

**Comment by nutjob4life** [comment]
@hoodriverheather to test this:

1. Visit https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-quality-reports/
2. You should be prompted to log in; try logging in with a non-Super User account.
3. You should get "Your account doesn't have access to this page. To proceed, please log in with an account that has access."
4. Try logging in with a Super User account
5. You should get the data quality report

**Comment by hoodriverheather** [comment]
@nutjob4life i tried with my htest account (I know it's not a Super User account). I'm not getting a message "Your account doesn't have access to this page...." message. But, I don't see the report either. Seem to be just on the login page (see screen shot).
What permissions does htest have? Or what groups is it in?
<img width="1328" alt="Screen Shot 2023-01-12 at 1 59 01 PM" src="https://user-images.githubusercontent.com/58526347/212190796-c7eb1932-4432-432a-9c29-51f684812948.png">

Also, I would change the titles in the totals boxes to match the titles in the report. For example: 
<img width="1024" alt="Screen Shot 2023-01-12 at 2 06 25 PM" src="https://user-images.githubusercontent.com/58526347/212191642-01563d1b-72ba-48d8-bbdf-8ffaf7a604b0.png">

**Comment by nutjob4life** [comment]
@hoodriverheather I see the message "Your account doesn't have access to this page" in your screenshot.

I'll change the summary boxes per your suggestion.

**Comment by hoodriverheather** [comment]
Ahhh - I see it. Whew!
Can you make that line bold?

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this note that Login admonitions now appear in "bg-warning" (orange) or "bg-danger" (red) depending on severity and that the stat boxes use the same text as the report.
