### ISSUE TITLE
Add page descriptions

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#202]
Visit https://edrn.nci.nih.gov/admin/pages/3/add_subpage/ and you'll see that only one of the possible content types has a description:

<img width="393" alt="Screenshot 2023-01-10 at 8 51 45 AM" src="https://user-images.githubusercontent.com/814813/211583577-d8f46fb8-7544-47b9-9f07-de6acd5c9ee0.png">

They should all have descriptions.

**Comment by hoodriverheather** [comment]
@nutjob4life I'm not seeing descriptions. See attached screen shot - 
<img width="1322" alt="Screen Shot 2023-01-12 at 2 11 28 PM" src="https://user-images.githubusercontent.com/58526347/212192840-4227b744-2def-4cb7-8586-8ca52b3eb795.png">

Would it be possible to have description based on the content type?  

- person use their EDRN Title, if EDRN title is blank have some default text?
- site use the Member Type, if blank - default text?
- etc.
If this is possible, you could send me a list of content types and we could come up with a value to use and if blank what to use for default text.

**Comment by nutjob4life** [comment]
@hoodriverheather this is referring to the Wagtail admin interface. 

BROKEN: _In the current production site_, https://edrn.nci.nih.gov/admin/pages/3/add_subpage/ shows only one content type description:

<img width="393" alt="211583577-d8f46fb8-7544-47b9-9f07-de6acd5c9ee0" src="https://user-images.githubusercontent.com/814813/212416348-a3f0b0d0-e32f-4978-b94b-1115feaa5aaf.png">

FIXED: Compare that _with the current dev site_, https://edrn-dev.jpl.nasa.gov/portal/renaissance/admin/pages/3/add_subpage/ and now every content type has a description:

<img width="884" alt="Screenshot 2023-01-13 at 2 44 15 PM" src="https://user-images.githubusercontent.com/814813/212416280-9a8b9f73-682f-42ec-90d2-528a1ac0fb6b.png">
