### ISSUE TITLE
Improvements to specimen reference sets

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#203]
- [x] Use checkmarks and blanks instead of "yes", "no" on specimen reference sets
- [x] Freeze header row
- [x] Make protocol ID link to protocol

**Comment by nutjob4life** [comment]
Possible solutions for freezing header row: https://stackoverflow.com/questions/8423768/freeze-the-top-row-for-an-html-table-only-fixed-table-header-scrolling

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this, visit https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/specimen-reference-sets/ and note the following:

- [ ] Checkmarks appear for "Yes", blank space for "No"
    -   👉 _However, note:_ in the [original table from Plone](https://edrn-dev.jpl.nasa.gov/portal/5/dev/data-and-resources/sample-reference-sets), the columns for Follow-up Data and Image Files are _all "no"_, and so I recommend dropping these columns completely. The table is already too wide for sect 508 max browser width (1200 pixels)
- [ ] Header row stays at the top (required a change to CSS so you may need to clear your cache)
- [ ] Protocol ID is now a hyperlink to the protocol (a new feature that the Plone version didn't have)

**Comment by hoodriverheather** [comment]
@nutjob4life this is great! We can ask DMCC about dropping columns now that we can edit - correct?

**Comment by nutjob4life** [comment]
@hoodriverheather yes, we can do it with software now or through Wagtail post-deployment into production.
