### ISSUE TITLE
Language review

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#204]
Here is a list of all of the HTML templates that go into the EDRN portal. I've made a first pass at drying up the language. Please review each template and let me know ones need further rewriting:

- [ ] Reduced wordiness for two login pages
- [ ] "No sites found" error condition needs better wording
- [x] https://github.com/EDRN/P5/blob/main/src/eke.biomarkers/src/eke/biomarkers/templates/eke.biomarkers/organ-study-card.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.biomarkers/src/eke/biomarkers/templates/eke.biomarkers/biomarker-organs.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.biomarkers/src/eke/biomarkers/templates/eke.biomarkers/certification.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.biomarkers/src/eke/biomarkers/templates/eke.biomarkers/private-biomarker.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.biomarkers/src/eke/biomarkers/templates/eke.biomarkers/biomarker-publications.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.biomarkers/src/eke/biomarkers/templates/eke.biomarkers/biomarker-resources.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.biomarkers/src/eke/biomarkers/templates/eke.biomarkers/biomarker-row.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.biomarkers/src/eke/biomarkers/templates/eke.biomarkers/biomarker.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.biomarkers/src/eke/biomarkers/templates/eke.biomarkers/biomarker-basics.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.biomarkers/src/eke/biomarkers/templates/eke.biomarkers/biomarker-studies.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.biomarkers/src/eke/biomarkers/templates/eke.biomarkers/biomarker-index.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.biomarkers/src/eke/biomarkers/templates/eke.biomarkers/biomarker-data-collections.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrnsite.content/build/lib/edrnsite/content/templates/edrnsite.content/home_page.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrnsite.content/build/lib/edrnsite/content/templates/edrnsite.content/flex_page.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrnsite.content/src/edrnsite/content/templates/edrnsite.content/home-page.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrnsite.content/src/edrnsite/content/templates/edrnsite.content/flex-page.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrnsite.content/src/edrnsite/content/templates/edrnsite.content/section-page.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrn.theme/src/edrn/theme/templates/edrn.theme/footer-menus.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrn.theme/src/edrn/theme/templates/edrn.theme/menus/main_menu.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrn.theme/src/edrn/theme/templates/edrn.theme/menus/sub_menu_dropdown.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrn.theme/src/edrn/theme/templates/edrn.theme/menus/footer_menu.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrn.theme/src/edrn/theme/templates/base.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrn.theme/src/edrn/theme/templates/includes/breadcrumbs.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrn.theme/src/edrn/theme/templates/includes/dev-warning.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrn.theme/src/edrn/theme/templates/includes/footer.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrn.theme/src/edrn/theme/templates/includes/header.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrn.theme/src/edrn/theme/templates/wagtailadmin/home.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrn.theme/src/edrn/theme/templates/wagtailadmin/base.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrn.theme/src/edrn/theme/templates/wagtailadmin/skeleton.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrn.theme/src/edrn/theme/templates/wagtailadmin/404.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrn.theme/src/edrn/theme/templates/wagtailadmin/login.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrn.theme/src/edrn/theme/templates/wagtailadmin/userbar/base.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrnsite.streams/build/lib/edrnsite/streams/templates/edrnsite.streams/rich_text_block.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrnsite.streams/build/lib/edrnsite/streams/templates/edrnsite.streams/cards_block.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrnsite.streams/src/edrnsite/streams/templates/edrnsite.streams/link.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrnsite.streams/src/edrnsite/streams/templates/edrnsite.streams/rich_text_block.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrnsite.streams/src/edrnsite/streams/templates/edrnsite.streams/title-block.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrnsite.streams/src/edrnsite/streams/templates/edrnsite.streams/table-block.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrnsite.streams/src/edrnsite/streams/templates/edrnsite.streams/site-section-cards-block.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrnsite.streams/src/edrnsite/streams/templates/edrnsite.streams/carousel-block.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrnsite.streams/src/edrnsite/streams/templates/edrnsite.streams/typed-table-block.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrnsite.streams/src/edrnsite/streams/templates/edrnsite.streams/site-section-card.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrnsite.streams/src/edrnsite/streams/templates/edrnsite.streams/cards-block.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrn.collabgroups/src/edrn/collabgroups/templates/edrn.collabgroups/committee-event.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrn.collabgroups/src/edrn/collabgroups/templates/edrn.collabgroups/chair-card.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrn.collabgroups/src/edrn/collabgroups/templates/edrn.collabgroups/committee.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrn.auth/src/edrn/auth/templates/edrn.auth/login.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrn.auth/src/edrn/auth/templates/edrn.auth/personal-links.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrn.auth/src/edrn/auth/templates/admin/login.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrn.auth/src/edrn/auth/templates/admin/base_site.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrn.metrics/src/edrn/metrics/templates/edrn.metrics/data-quality-report.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrn.metrics/src/edrn/metrics/templates/edrn.metrics/report-index.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.knowledge/build/lib/eke/knowledge/templates/eke.knowledge/knowledge-folder.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.knowledge/build/lib/eke/knowledge/templates/eke.knowledge/publication.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.knowledge/build/lib/eke/knowledge/templates/eke.knowledge/disease.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.knowledge/build/lib/eke/knowledge/templates/eke.knowledge/misc-resource.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.knowledge/build/lib/eke/knowledge/templates/eke.knowledge/knowledge-object.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.knowledge/build/lib/eke/knowledge/templates/eke.knowledge/publication-index.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.knowledge/src/eke/knowledge/templates/eke.knowledge/legend.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.knowledge/src/eke/knowledge/templates/eke.knowledge/protocol-index.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.knowledge/src/eke/knowledge/templates/eke.knowledge/member-finder-results.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.knowledge/src/eke/knowledge/templates/eke.knowledge/knowledge-folder.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.knowledge/src/eke/knowledge/templates/eke.knowledge/data-collection-row.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.knowledge/src/eke/knowledge/templates/eke.knowledge/faceted-vocab-checks.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.knowledge/src/eke/knowledge/templates/eke.knowledge/publication.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.knowledge/src/eke/knowledge/templates/eke.knowledge/member-finder-pis.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.knowledge/src/eke/knowledge/templates/eke.knowledge/disease.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.knowledge/src/eke/knowledge/templates/eke.knowledge/biomarker-developmental-laboratories.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.knowledge/src/eke/knowledge/templates/eke.knowledge/publication-row.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.knowledge/src/eke/knowledge/templates/eke.knowledge/protocol.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.knowledge/src/eke/knowledge/templates/eke.knowledge/member-finder-sites.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.knowledge/src/eke/knowledge/templates/eke.knowledge/data-collection-index.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.knowledge/src/eke/knowledge/templates/eke.knowledge/protocol-row.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.knowledge/src/eke/knowledge/templates/eke.knowledge/sites-by-type.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.knowledge/src/eke/knowledge/templates/eke.knowledge/misc-resource.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.knowledge/src/eke/knowledge/templates/eke.knowledge/member-finder-member-types.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.knowledge/src/eke/knowledge/templates/eke.knowledge/person.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.knowledge/src/eke/knowledge/templates/eke.knowledge/committee-index.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.knowledge/src/eke/knowledge/templates/eke.knowledge/faceted-vocab-selector.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.knowledge/src/eke/knowledge/templates/eke.knowledge/ingest-controls.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.knowledge/src/eke/knowledge/templates/eke.knowledge/knowledge-object.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.knowledge/src/eke/knowledge/templates/eke.knowledge/site-index.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.knowledge/src/eke/knowledge/templates/eke.knowledge/publication-index.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.knowledge/src/eke/knowledge/templates/eke.knowledge/member-finder.html
- [x] https://github.com/EDRN/P5/blob/main/src/eke.knowledge/src/eke/knowledge/templates/eke.knowledge/site.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrnsite.search/build/lib/edrnsite/search/templates/edrnsite.content/home_page.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrnsite.search/build/lib/edrnsite/search/templates/edrnsite.content/flex_page.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrnsite.search/src/edrnsite/search/templates/edrnsite.search/search.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrnsite.ploneimport/src/edrnsite/ploneimport/templates/edrnsite.ploneimport/event-view.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrnsite.ploneimport/src/edrnsite/ploneimport/templates/edrnsite.ploneimport/link-view.html
- [x] https://github.com/EDRN/P5/blob/main/src/edrnsite.ploneimport/src/edrnsite/ploneimport/templates/edrnsite.ploneimport/folder-view.html

**Comment by hoodriverheather** [comment]
@nutjob4life Wow! Lots of pages - whew! For the most part these all look great. I had some minor comments below and think we should open a few issues for some items in the next release. Let me know if any of these items don't make sense.

Here's what I found/think:

I think that when the message is "...available only to users who login with correct permissions" the message could be "Login to view additional ..." I only saw this on the first few pages in the list.

I haven't been a programmer for many years, so let me know if the suggestions make sense with the actions in the UI!

See below for possible updates for this page https://github.com/EDRN/P5/blob/main/src/eke.biomarkers/src/eke/biomarkers/templates/eke.biomarkers/biomarker-organs.html

<img width="1402" alt="Screenshot 2023-01-23 at 12 57 32 PM" src="https://user-images.githubusercontent.com/58526347/214153631-c90668c7-f40a-44ea-addf-eae703c81f2e.png">

Does it make sense to change the message "There are no PIs" to "No PIs found" or something else? I'm unsure when a user would get this message.

https://github.com/EDRN/P5/blob/main/src/eke.knowledge/src/eke/knowledge/templates/eke.knowledge/member-finder-pis.html
Also, unsure when user would get the message "There are no sites". Maybe we can discuss if these messages should be changed?
https://github.com/EDRN/P5/blob/main/src/eke.knowledge/src/eke/knowledge/templates/eke.knowledge/member-finder-sites.html

Remove "and possibly nowhere as some of these resources are not maintained" from the page below. We should confirm those pages and either find the correct link or remove if they no longer exist.
https://github.com/EDRN/P5/blob/main/src/eke.knowledge/src/eke/knowledge/templates/eke.knowledge/misc-resource.html

For this page - https://github.com/EDRN/P5/blob/main/src/eke.knowledge/src/eke/knowledge/templates/eke.knowledge/person.html
 Update this message "No code was assigned by the DMCC to identify this person; this may be the case for non-EDRN people" to say "No person code assigned for this person; this may be the case for non-EDRN people"


The unchecked urls returned 404s. Maybe they moved or were deleted?

New issues to address in next release:
This login page has a lot of words and information. I think we could try to reduce words, make more concise and provide users with link if they don't have permissions.
 
 https://github.com/EDRN/P5/blob/main/src/edrn.auth/src/edrn/auth/templates/edrn.auth/login.html 
https://github.com/EDRN/P5/blob/main/src/edrn.auth/src/edrn/auth/templates/admin/login.html


WDYT about opening a new issue for the next release to include additional rules to populate text for the search descriptions based on updates we can get from DMCC in their SOAP API?

**Comment by nutjob4life** [comment]
@hoodriverheather Changes made as follows:

-   `biomarker-organs.html`
    -   Log in text now reads `Log in to view additional supplemental information`
    -   Organ-missing text is now `No organ-specific information has been specified for this biomarker`
-   `member-finder-pis.html` now has `No PIs found.`
-   `member-finder-sites.html` and `site-index.html`
    -   You should never get `There are no sites` because this indicates an error condition, like a catastrophic failure of the database. But I think we need to show _something_ here and not just a blank page. What do you think?
-   `misc-resources.html`
    -   Changed to `(will take you off site)`
    -   Updating these 404s I think is beyond the scope of the portal. These need to be fixed in the Biomarker Database. I've [filed an issue there](https://github.com/EDRN/biomarker-database/issues/55) to track it.
-   `person.html` text now reads `No person code assigned for this person; this may be the case for non-EDRN people`
-   The 404s in the checklist were inadvertently included; I've marked them as completed
-   `login.html` (in two places) let me know the new wording to include.

Also, no need to ask about opening a new issue. I would always, _always_ go ahead and file an issue! Nike has the right advice here: Just Do It™ 😁

**Comment by hoodriverheather** [comment]
@nutjob4life Thanks! This is great!
