### ISSUE TITLE
Add link to a person's site on the person's page

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#208]
## 🤔 Tell Us About the Feature

Christos Patriotis wants the link to the person's site (which is available in the breadcrumbs) to appear on the right side under the person's portrait.

And if we're going to be updating the `person.html` template, we may as well fill in a "no title assigned" value to the many, many people who do not have an EDRN title in the RDF.

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this visit https://edrn-dev.jpl.nasa.gov/portal/renaissance/about-edrn/sites/230-arizona-state-university/anderson-karen/ and notice the extra site link under the photo and "(no title assigned)" under EDRN Title.

**Comment by hoodriverheather** [comment]
@nutjob4life If the EDRN Title is blank for so many people, should we really show it?

**Comment by nutjob4life** [comment]
Commit c1bf099 does the following:
- If there is an EDRN title, the text `EDRN Title` appears, followed by the EDRN title on the next line
- If there is no EDRN title, then nothing appears

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this:

1. Confirm that there's a link to the person's site not only in the breadcrumbs (which has always been there) but also below the photo (Christos's request)
2. Confirm that the EDRN title and the label `EDRN Title` only appears if the person has an EDRN title.

To help with ❷, some people with titles are:

- Rowland Jr., Kendrith
- Shaheen, Nicholas
- Oropeza, Erica

Some people without titles are:

- Harkey, Zachery
- McWilliams, Kristin
- Thompson, Hannah
