### ISSUE TITLE
Investigators repeating in Protocols

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#21]
Investigators repeating in protocols. It seems to be happening in every protocol – here are a few links:
https://edrn.jpl.nasa.gov/protocols/421-a-biomarker-bakeoff-in-early-stage-pancreatic
 
https://edrn.jpl.nasa.gov/protocols/258-a-methylation-panel-for-bladder-cancer
 
https://edrn.jpl.nasa.gov/protocols/447-an-automated-system-for-breast-cancer
https://edrn.jpl.nasa.gov/protocols/434-a-prospective-study-to-establish-a-new-onset

**Comment by nutjob4life** [comment]
Interesting; I'm not seeing this on a new portal. But it could be related to subsequent ingest, perhaps re-adding investigators already there. I'm running an ingest in my lab to see if that duplicates investigators.

**Comment by nutjob4life** [comment]
OK, confirmed. On a brand new portal, if a protocol as _n_ investigators, then after ingest it will have _2n_; after another ingest, _3n_, etc.

**Comment by nutjob4life** [comment]
Fixed in 06355478cf2c5119e0d803e915f0896e060ca426

**Comment by nutjob4life** [comment]
@hoodriverheather to confirm this is fixed, it needs to be tested before and after a full ingest; the issue occurred after a full ingest happened.
