### ISSUE TITLE
It's hard to find the NCI PO/PD contact person associated with each organ

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#210]
## 🤔 Tell Us About the Feature

Amanda Skarlupka says it's hard to find the NCI PO/PD contact person associated with each organ.

**Comment by nutjob4life** [comment]
Next steps: see if PO/PD contact info can come from DMCC's SOAP API.

**Comment by hoodriverheather** [comment]
@nutjob4life I think it's still an issue. When i go to the portal and look at the Breast group https://edrn.nci.nih.gov/about-edrn/groups/breast-and-gynecologic-cancers-research-group/ I can't see who the NCI Program Director is for that group. However, the group members probably all know. That's something the DMCC would need to send - correct?

**Comment by nutjob4life** [comment]
@hoodriverheather I think so! Unless someone else has that info, and if it needs to go to the "Sites" page, then the DMCC would need to provide that.

**Comment by hoodriverheather** [comment]
@nutjob4life I thought we used to have that on the Portal. Maybe that was a hand edited field in Plone? I don't think the program directors change often.

**Comment by hoodriverheather** [comment]
@nutjob4life I think we used to have them on the Collaborative groups pages. Example: https://edrn.nci.nih.gov/about-edrn/groups/breast-and-gynecologic-cancers-research-group/

Would you be able to have another category heading on the right that says NCI Program Director (or whatever is appropriate?), then list the NCI person?

**Comment by nutjob4life** [comment]
Okay so not on the [Sites](https://edrn.nci.nih.gov/about-edrn/sites/) page, but on each of the collaborative groups; got it

**Comment by nutjob4life** [comment]
Okay @hoodriverheather to QC this:

1. Visit the [breast collaborative group](https://edrn-dev.jpl.nasa.gov/portal/renaissance/about-edrn/groups/breast-any-gynecologic-cancers-research-group/)
2. Log in with editor or better permissions
3. On the right side, take note that their is no NCI Program Director
4. Click the NIH badge and choose "Edit this page"
5. In the field for program director, enter any text
6. Click "Publish", then "View Liive"
7. On the right side, note that there is now an NCI Program Director with the text you entered
8. Repeat with the remaining groups, if you wish 😉

**Comment by hoodriverheather** [comment]
@nutjob4life I successfully added Christos to the Breast group https://edrn-dev.jpl.nasa.gov/portal/renaissance/about-edrn/groups/breast-and-gynecologic-cancers-research-group/ However, i noticed he isn't listed as a member on the Public Portal, but he is listed as a member on the DMCC site - https://www.compass.fhcrc.org/edrns/cgi-bin/cgroup/co_breast.asp?p=group

I didn't look to see if there are any other differences, but would be good to check.

**Comment by nutjob4life** [comment]
@hoodriverheather according to the DMCC's SOAP, Christos's person № is 2313.

Also according to their SOAP, the chair of the breast group is person № 1736, and the co-chair is № 1076. The members are the following:

- 1015
- 1760
- 1898
- 1911
- 1974
- 2755
- 2823
- 3205
- 3248
- 3728
- 3734
- 3749
- 3788
- 4284
- 4875
- 4959
- 4976
- 5011
- 5230
- 5433

Person № 2313 is not in that list. Better follow up with the DMCC!

**Comment by hoodriverheather** [comment]
@nutjob4life My understanding is that every PO/PD should be a member of EDRN. How do you want to follow up with DMCC?

**Comment by nutjob4life** [comment]
This might be a problem on our end after all. When I looked at the raw over-the-wire data, I see person 2313 show up twice. And when I run the CancerDataExpo locally, I get 2313 in both the Data Sharing committee and the Breast group.

Continuing to debug!

**Comment by nutjob4life** [comment]
@hoodriverheather the problem turned out to be unknown roles that the DMCC added to the SOAP data. I updated the [CancerDataExpo](https://github.com/EDRN/CancerDataExpo) to treat those roles as additional members. After installing the new CancerDataExpo, I then did a full ingest on the dev portal. Christos now appears [in the breast group](tps://edrn-dev.jpl.nasa.gov/portal/renaissance/about-edrn/groups/breast-and-gynecologic-cancers-research-group/).

We don't need to followup with the DMCC now.

**Comment by hoodriverheather** [comment]
@nutjob4life Woot! Thanks for figuring that out!

**Comment by hoodriverheather** [comment]
@nutjob4life i'm reopening and waiting for Jackie's response.

**Comment by nutjob4life** [comment]
@hoodriverheather I saw Jackie's response so I've filed [an issue in the CancerDataExpo](https://github.com/EDRN/CancerDataExpo/issues/24) to support `Project Scientist` and `Program Officer`.

Once the new CancerDataExpo is in place, I can then update Portal 6.7 to support these as well.

**Comment by nutjob4life** [comment]
@hoodriverheather the CancerDataExpo is now updated to accommodate `Project Scientist` and `Program Officer` and put those into the RDF.

This means Christos will disappear as a plain "member" from the dev portal until I can update the portal code to display the new roles—which I'm going to work on next.

**Comment by nutjob4life** [comment]
@hoodriverheather okay this is now ready for testing on the [dev portal](https://edrn-dev.jpl.nasa.gov/portal/renaissance/).

To test it , go to About EDRN → Committees and Collaborative Groups, then try each of the collaborative groups as well as the committees (logging in as needed).

- For the breast group, there should be no program officer but two project scientists
- For the GI group, there should be one program officer and two project scientists
- For the lung group, there should be two program officers and one project scientist
- For the prostate group, there should be one of each
- The rest of the committees, sub-committees, groups, and the one team on this page should not have any program officers or project scientists

**Comment by hoodriverheather** [comment]
@nutjob4life Thanks for making this update so quickly!

**Comment by nutjob4life** [comment]
@hoodriverheather you're welcome! I see the QC label, so closing this 🎉
