### ISSUE TITLE
Collaborative Group missing from protocol

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#211]
## 🐛 Describe the Bug
Collaborative Group value is missing on Public Portal, but appears on COMPASS site. Below are the few that I checked. Not sure if this is happening on all/other protocols. 

Also, would it be possible to get additional values added to the Protocol Page:

- Project/Protocol Type
- Cancer Type

Are they part of the RDF from DMCC? 

See the following:

https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/protocols/431-breast-reference-set-application-jendoubi-milagen-2017/
<img width="1268" alt="Screen Shot 2023-01-12 at 2 32 49 PM" src="https://user-images.githubusercontent.com/58526347/212197391-9491d6c2-72ff-4ee9-b8b9-a3a7944aabba.png">
<img width="1190" alt="Screen Shot 2023-01-12 at 2 34 20 PM" src="https://user-images.githubusercontent.com/58526347/212197395-9813d5b2-a3e4-4ee6-8915-f18022df101b.png">

https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/protocols/452-breast-reference-set-application-paulovich-2018/

<img width="1100" alt="Screen Shot 2023-01-12 at 2 43 00 PM" src="https://user-images.githubusercontent.com/58526347/212197430-5fa2be7a-32d0-4319-ac53-d823817d7fea.png">

**Comment by nutjob4life** [comment]
@hoodriverheather "project/protocol type"? Not sure what this is. The RDF has a flag that indicates if an entry is a plain protocol or a team project. And we badge the entries that are team projects with this indicator:
<img width="145" alt="Screenshot 2023-01-14 at 3 39 11 PM" src="https://user-images.githubusercontent.com/814813/212498189-bf9451cd-c2b9-4de5-a23a-a1827ef1fa36.png">
The next build of 6.0.2 will include cancer types in the protocol display:
<img width="497" alt="Screenshot 2023-01-14 at 3 47 09 PM" src="https://user-images.githubusercontent.com/814813/212498494-077f6d4f-e1e1-4832-81bf-24d4b0951258.png">

**Comment by hoodriverheather** [comment]
@nutjob4life Looks like you were able to now show Collab Group. The other field that's labeled project/protocol type is shown in the screen shot from the secure site at DMCC. For this protocol it says Reference Set. I was thinking that would be great info to show under the description, instead of no description available. We could ask DMCC to add it.
I know Dan doesn't like the "no description available", so I was looking for other descriptive text we could put there.

**Comment by hoodriverheather** [comment]
@nutjob4life List of Protocols seems to only show a single value for Collaborative Group. The following protocol ID 104 has both Breast/GYN and Lung listed, but only Breast/GYN is showing on the list.
https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/protocols/


https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/protocols/104-assessment-of-clinical-potential-of-digital-snp-analysis/

see screen shot:
<img width="1305" alt="Screen Shot 2023-01-14 at 3 19 28 PM" src="https://user-images.githubusercontent.com/58526347/212501344-7abfa849-ab5f-4def-b747-23f20cc5e763.png">

**Comment by nutjob4life** [comment]
@hoodriverheather:

- If a protocol has an abstract, the first 200 characters of it will be used in the search results page. If not, then then the text "TITLE is a protocol, project, or study that is being pursued or was pursued by the Early Detection Research Network." appears, where TITLE is the name of the protocol.
- Protocols that belong to multiple collaborative groups now show all their groups on the protocol index page.
