### ISSUE TITLE
Header in reports unreadable

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#212]
In `Message-ID: <9307B05D-653C-4791-A48A-75FBA308B323@jpl.nasa.gov>`, @dcrichto1 wrote:

> If you click on the reports on the biomarker page on the portal (copy, Excel, CSV, etc), the header of these seems to be somewhat unreadable.   I think it is the merger of the values.  The CSV looks somewhat corrupted in the header.  Can you check these?  I didn’t look at data and other pages.

**Comment by nutjob4life** [comment]
Confirmed behavior in

- Copy to clipboard
- Excel generation
- CSV generation
- PDF generation

Confirmed on

- [ ] Biomarkers
- [ ] Protocols
- [ ] Science data
- [ ] Publications

Fix will require using exportOptions on datatables and making a custom JavaScript function to generate the header row

**Comment by hoodriverheather** [comment]
@nutjob4life Looks great!
