### ISSUE TITLE
Member Finder under 2 categories on home page, but not drop down menus

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#213]
The member finder link is located under both the Work with EDRN and About EDRN groups on the home page - https://edrn-dev.jpl.nasa.gov/portal/renaissance/
But isn't in any pull down lists. I think we should put it in one of the categories and add it to that pull down. I think Work with EDRN? IDK. :)

**Comment by nutjob4life** [comment]
We can't put the Member Finder in any of the menus because it's a Django _view_ and not a Wagtail _page_. That's why I'm trying to make sure to prominently link it from other pages where we can put the link.

**Comment by nutjob4life** [comment]
@hoodriverheather see above comment ↑

However, if you think it's worth the time, we could create a single new page type called "Member Finder" who's template is the Django view. It's a lot of extra overhead but it would allow it to appear in a pulldown menu.

Is this a 6.0.2 or 6.0.3 issue?

**Comment by hoodriverheather** [comment]
@nutjob4life Not worth the time at this point. Dan also thinks it's ok to keep under both "categories" or cards on the home page.

**Comment by nutjob4life** [comment]
@hoodriverheather this is now live on the dev portal. You should see it in the drop down menu. The link on the Sites page is also updated. QC and close if you're happy!

There's a [post-live issue](https://github.com/EDRN/P5/issues/304) that we'll have to do once it's live.

**Comment by hoodriverheather** [comment]
@nutjob4life looks great!
