### ISSUE TITLE
Make Groups a sibling of "Mission and Structure" instead of child of it

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#217]
What the title says.

Impetus: so that "Collaborative Groups and Committees" appears on the main navigation menu

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this, visit https://edrn-dev.jpl.nasa.gov/portal/renaissance and notice that COMMITTEES AND COLLABORATIVE GROUPS is now on the "ABOUT EDRN" menu.

**Comment by hoodriverheather** [comment]
@nutjob4life I'm good if you want to do a rebuild.

**Comment by nutjob4life** [comment]
@hoodriverheather started now. Last build took 14 minutes.
