### ISSUE TITLE
Ziding is showing up twice 

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#218]
## 🐛 Describe the Bug
When I search for "Ziding" in the text search, the return result is two Ziding Feng records. One has person ID 993 and the other has person id 5115. I think 5115 is an error and shouldn't be sent from DMCC.

**Comment by nutjob4life** [comment]
@hoodriverheather The RDF shows

- Person 993 from site 5 with employment = `Current employee`
- Person 5115 from site 151 with employment = `Current employee`

Why is this a portal bug?

**Comment by nutjob4life** [comment]
Next step: glean info from DMCC about Ziding's cloning program.

**Comment by nutjob4life** [comment]
Closing this as we've discovered that Ziding is a Co-I at MD Anderson; that's why there's two.
