### ISSUE TITLE
Protocol missing Lead PI

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#22]
The Lead Investigator is missing from Protocol 421. When looking at this protocol on the EDRN portal that’s running at NCI it shows Randall Brand as the Lead PI - https://edrn.nci.nih.gov/protocols/421-a-biomarker-bakeoff-in-early-stage-pancreatic

**Comment by nutjob4life** [comment]
I think P4 is actually showing the wrong behavior and P5 is correct in showing no PI for protocol 421.

The RDF for protocols contains:
```xml
<rdf:Description rdf:about="http://edrn.nci.nih.gov/data/protocols/421">
    <ns2:title>A Biomarker  Bakeoff in Early Stage Pancreatic Cancer</ns2:title>
    <ns1:abbreviatedName>Pan Ca Bakeoff</ns1:abbreviatedName>
    <ns1:protocolType>Collaboration</ns1:protocolType>
    <ns1:projectFlag>Project</ns1:projectFlag>
    <ns1:leadInvestigatorSite rdf:resource="http://edrn.nci.nih.gov/data/sites/827"/>
    …
</rdf:Description>
```
The RDF for sites, though, does *not* contain `http://edrn.nci.nih.gov/data/sites/827`. And sure enough, this site isn't on P5 at all.

It's also not on the DMCC. If you search for the old site's PI (Russell Brand) on the Secure Site, you get no results.
