### ISSUE TITLE
Update login page text

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#223]
# ✋ Hold it!
@nutjob4life I might be able to edit this myself, but I will start this so that we can discuss potential updates.
- place holder - still working on updates.

**Comment by nutjob4life** [comment]
@hoodriverheather you can edit some of the login page text here: https://edrn.nci.nih.gov/admin/snippets/edrnsitecontent/boilerplatesnippet/

The interface is a little ugly but it works. You can edit anything from the "Important Login Information" down.

**Comment by nutjob4life** [comment]
Also: that "US Government Warning" part pretty much has to stay exactly as is.

**Comment by nutjob4life** [comment]
@hoodriverheather I seem to recall you had a diagram of changes you wanted to the login form. Could you attach it to this issue?

**Comment by hoodriverheather** [comment]
<img width="652" alt="PortalLoginUpdates" src="https://github.com/EDRN/P5/assets/58526347/5f2bb777-294e-4046-98d9-a7d2744b076e">

**Comment by nutjob4life** [comment]
Making the changes I can through-the-web

**Comment by nutjob4life** [comment]
Closing this for now!
