### ISSUE TITLE
update member directory page

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#23]
Add text box search and faceted search.
Faceted search by PI, by site, maybe by funding type.
Can the faceted search allow you to start typing and then show matching entries? Just trying to get around these lists being so long. IDK.

**Comment by nutjob4life** [comment]
FYI @hoodriverheather there already is a faceted search by PI, site, and member type; see https://edrn.nci.nih.gov/members-list

**Comment by nutjob4life** [comment]
> Can the faceted search allow you to start typing and then show matching entries?

@hoodriverheather that would be great, but researching the [faceted navigation add-on for Plone](https://pypi.org/project/eea.facetednavigation/) suggests that'd it's not fully supported and/or require installation of [Solr](https://lucene.apache.org/solr/).

I can carve out (a lot of) time to check it out, but according to analytics the `/members-list` page view was less than 1% for 2019. I'd like to suggest adding just a plain text search box above the other facets that are *already there* and see if that makes it a little more useful.

**Comment by hoodriverheather** [comment]
This works great!
