### ISSUE TITLE
Site organization using "MemberGroup" info

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#233]
## 🤔 Tell Us About the Feature

The DMCC SOAP API is now enabling the "secure" site to provide information on how to organize the display of sites, including organ groups, organ group numbers, top dogs, etc.

## 🎇 What Solution You'd Like

The portal should use this information to organize the sites page.

## 🗺 Context

Currently [blocked by this issue](https://github.com/EDRN/CancerDataExpo/issues/20).

**Comment by nutjob4life** [comment]
@hoodriverheather to test this:

1. Visit https://edrn-dev.jpl.nasa.gov/portal/renaissance/
2. Click "Sites" in the global navigation; or click "Sites" in the "About EDRN" card on the home page; or, click "About EDRN" directly on that card and then click the "Sites" card.
3. Compare the results on that page with the sub-pages at https://www.compass.fhcrc.org/edrns/cgi-bin/member/member.asp?p=member and ensure the information matches.

Please note there is a problem with the upstream data from the DMCC:

Abhijit Patel, person 4951, according to the DMCC's "Registered_Person" SOAP API has site 1013. But according to the "Sites" SOAP API, there is no such site 1013. The "Member_Group"  SOAP API mentions person 4951 as being the MPI in group 2 for ovary for site 1002 as a BDL. There is a mismatch.

Because the portal insists on matching a person to the site, Abhijit Patel will not be listed as the MPI for ovary in group 2 as a BDL.

The "secure" site's staff directory was searched for person 4951, but gives "member not found". Searching by name for Abhijit Patel gives person 4875.

Now, person 4875 appears in the "Registered_Person" SOAP API and is named Abhijit Patel and has site 1002. And, curiously, that appears in the "MemberGroup" SOAP API for site 1002 in group 2 for ovary as a BCC. The portal will show the person under the BCCs.

It's possible that both the "Registered_Person" and "Member_Group" SOAP APIs believe person 4951 is a ghost.

Regardless, there are two Abhijit Patels in the upstream data from the DMCC appearing in two different places ("Registered_Person" and "MemberGroup" SOAP APIs) but one (4951) is a ghost and the other (4875) is the real one.

**Comment by hoodriverheather** [comment]
@nutjob4life This looks great and even your favorite investigator Cecilia is showing up correctly ;)

Not sure I'm remembering correctly, but should there also be descriptions of each awarded project under each group? Or is that another page?

**Comment by nutjob4life** [comment]
Nooo, not Cecilia! 😱

In an effort to make these pages appear more like the DMCC's, all that extra text has moved to each site's page. Click through to a site to read it.

**Comment by hoodriverheather** [comment]
@nutjob4life I think the summary under each group was really helpful on the main list. Is that easy to put back?

**Comment by nutjob4life** [comment]
@hoodriverheather it's … not easy 😅

But I'll see if I can put it back and remove the summary text from the individual site views like bfore.

**Comment by nutjob4life** [comment]
@hoodriverheather okay, try it now:

https://edrn-dev.jpl.nasa.gov/portal/renaissance/about-edrn/sites/

**Comment by hoodriverheather** [comment]
@nutjob4life You Rock! I think this is good to go 👍

**Comment by nutjob4life** [comment]
@hoodriverheather thank you!
