### ISSUE TITLE
Upgrade path for 6.0.5 → 6.1.0

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#234]
## 🤔 Tell Us About the Feature

Now that 6.0.5 is live, we now need a new upgrade path for the [next milestone, 6.1.0](https://github.com/EDRN/P5/milestone/12).

## 🎇 What Solution You'd Like

Ideally something that works in these environments:

-   Developer desktop
-   tumor.jpl.nasa.gov Jenkins
-   CBIIT tiers
    -    dev tier
    -    stage tier
    -    prod tier

**Comment by nutjob4life** [comment]
Updated the following:

- `support/devrebuild.sh`
- Jenkins
- `support/cbiit-deploy.sh` which handles the dev and stage tiers
- `support/cbiit-deploy-prod.sh` which handles the stage (when simulating prod) and prod tiers

**Comment by hoodriverheather** [comment]
Not tested, but sure this is fine :)

**Comment by nutjob4life** [comment]
@hoodriverheather then I'll go ahead and add the QC label! 🎊
