### ISSUE TITLE
Grady BCC Site Summary starts with T

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#235]
William Grady's site summary on the Sites page  - https://edrn.nci.nih.gov/about-edrn/sites/#brls has a typo at the beginning. Please remove the "T".
Screenshot -

![Image](https://user-images.githubusercontent.com/58526347/221046054-70f38ab9-270e-4a8a-9ed3-7fd5c0cc73cd.png)

**Comment by nutjob4life** [comment]
Cannot remove the `T`; this comes from the upstream RDF—which comes from the upstream DMCC SOAP. Here's the actual data as it comes across the wire, with the `T`:
<img width="573" alt="TGastrointestinal" src="https://user-images.githubusercontent.com/814813/221064787-41d87051-e372-4c2b-a700-6bdac6ec736c.png">
The DMCC will have to fix this, sorry!

**Comment by hoodriverheather** [comment]
@nutjob4life Do we have any other RDF fixes we need to report to DMCC?

**Comment by hoodriverheather** [comment]
Reported to DMCC for them to fix.
