### ISSUE TITLE
EDRN BRL PI not Listed Correctly

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#236]
The PI of the Fred Hutch BCC-BRL has let me know that on the EDRN Website, they are listed in an incorrect location and are shown as a PI Under the BDL with Dr. Grady and not as the PI of the Fred Hutch BRL.

Dr. Cecilia Yeung and Dr. William Grady are MPI’s of the Fred Hutch BCC.
Dr. Cecilia Yeung, is the PI of the BRL, and not a PI of a BDL.

<img width="1176" alt="Screenshot 2023-02-23 at 2 41 59 PM" src="https://user-images.githubusercontent.com/58526347/221047223-c5d23bf9-6ad8-4841-bdd5-e1914d3cbb67.png">

**Comment by nutjob4life** [comment]
Obsoleted by #233.

See the new display of site information at: https://edrn-dev.jpl.nasa.gov/portal/renaissance/about-edrn/sites/
