### ISSUE TITLE
Member finder - only finds one Ziding Feng

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#237]
## 🐛 Describe the Bug
member finder - https://edrn.nci.nih.gov/find-members#pi=Feng%2C%20Ziding
only finds one Ziding, but when you use search it finds 2. One for the Fred Hutch site and one for MD Anderson (Jackie confirmed this is correct).
Shouldn't these both find 2 Ziding's? 

<img width="1296" alt="Screenshot 2023-02-23 at 4 55 45 PM" src="https://user-images.githubusercontent.com/58526347/221066069-7d6d1cdd-ee63-4e11-9e02-9c54bc4fcb4b.png">
<img width="1213" alt="Screenshot 2023-02-23 at 4 56 04 PM" src="https://user-images.githubusercontent.com/58526347/221066076-d28a0c7a-0bf2-4cd0-92c3-bbc1d12521a9.png">

**Comment by nutjob4life** [comment]
I don't think so. The "member finder" searches by principal investigators. Ziding Feng is a member of two sites (Fred Hutch and MD Anderson) but he's only a PI at one (Fred Hutch). The PI at MD Anderson is Samir Hanash.
