### ISSUE TITLE
Metadata Collection Form

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#238]
See https://app.diagrams.net/#G1P7zvvPydbZ08-epAvsg_vZUL0Wgz_AwS

**Comment by nutjob4life** [comment]
@hoodriverheather I have a prototype here:

https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/metadata-collection-form/

Since there's no CAPTCHA, I think we should require a login to access it. If it needs to be open to the public, we'll add a CAPTCHA.

Some differences from your wireframe:

-   If I let the formatting be automatic, it's a lot less code but it puts all the widgets into a single column and not like your wireframe. Is that okay?
    -    If not, it's a lot more code to make a custom layout
-   I made the Data Custodian required (and defaulting to the currently logged in user) just so I can reference them by name (and email) in the "landing page". If those truly need to be optional, I'll rewrite the landing page to not reference the user by name.
-   Discipline, Data Category, and Species are free text because the portal does not ingest anything from KSDB. (And as far as I can tell, the only KSDB instance is for MCL, not EDRN.)
-   There's no validation on the text box that becomes `OwnerPrincipal`
-   The wireframe didn't have a box for what becomes `MethodDetails` so I added one
-    I'm not sure what these fields should get called in the generated `.cfg` file: ref URL, ref URL description, DOI, DOI URL.

When you hit Submit, the portal generates a collection-level `.cfg` file and emails it. Right now the email goes to you and me while we test.

**Comment by hoodriverheather** [comment]
@nutjob4life It's looking good! I wonder if we could provide pick list values in the form right now for the items that are coming from KDSB? Eventually we could decide to pull from KSDB if people really use the form :) 
I really like the description text that you have on some of the items. I'll take a closer look to provide descriptions for some of the other fields.
Do you think you could create the .cfg using Asitang's key value pairs? We haven't done this yet in LabCAS, but it how we want to move forward.https://github.com/EDRN/labcas_publish/commit/a02c1a7d7b1f6c7ffe1215d775993eb3c746d83a

**Comment by nutjob4life** [comment]
@hoodriverheather You got it!

If you can tell me the current permissible values in KSDB, I can put them in. (I tried logging into KSDB but neither my EDRN nor my Consortium for Molecular and Cellular Characterization of Screen-Detected Lesions passwords work).

As for @asitang's key-value pairs, could you tell me which lines need to change?
```ini
[Collection]
CollectionName = Heather Test
CollectionDescription = This is a test collection description.
Discipline = Genomics
DataCategory = RNA Sequencing
Institution = NASA Jet Propulsion Laboratory
InstitutionId = 128
LeadPI = Crichton, Dan
LeadPIId = 1075
DataCustodian = Heather Kincaid
DataCustodianEmail = heather.kincaid@jpl.nasa.gov
Organ = Blood
OrganId = 2
CollaborativeGroup = lung
Consortium = EDRN
ProtocolName = Standard Specimen Reference Set:  Prostate
ProtocolId = 120
Species = Homo Sapiens
OwnerPrincipal = cn=JPL,dc=edrn,dc=jpl,dc=nasa,dc=gov|cn=DMCC,dc=edrn,dc=jpl,dc=nasa,dc=gov
```
I read over [that link](https://github.com/EDRN/labcas_publish/commit/a02c1a7d7b1f6c7ffe1215d775993eb3c746d83a), but I don't understand what it's supposed to be (and why aren't you guys just using RDF subject URIs‽).

So instead of

    ProtocolName = Standard Specimen Reference Set:  Prostate

it's supposed to be

    ProtocolName = Protocol_ProtocolID_120

Is that right? What other lines above are affected? 🤷‍♀️

**Comment by hoodriverheather** [comment]
@nutjob4life 
Here's the list for Discipline:
Genomics
Proteomics
Pathology Images
Radiology
Immunology
Pathology
Undefined

Here's the list for Data Category:
Sequencing
RNA Sequencing
DNA Methylation Sequencing
DNA Microarray Analysis
Mass Spectrometry
Whole Slide Imaging
Tissue Micro Array
Immunohistochemestry
CT
MRI
Mammography
Fluoroscopy
PET
Documentation
Biospecimen
Clinical
Immunoassay
ELISA
Luminex
LabMAP
Protein Microarray
Single Slide Image
Multiplex-Immunoflourescent Staining
Radiomics
Antibody Microarray

This google sheet actually has more current values than KSDB. https://docs.google.com/spreadsheets/d/1jvoSqXNupkV6T7Ptn7vtH2Iszx09sWvysRb8q8nSSpw/edit#gid=0

As for the key value pairs. It would be best to ask @asitang  the format of the values and why we aren't using RDF subject URIs. I think we would use this for the following:
Institution, LeadPI, Organ. Any pick lists.

**Comment by nutjob4life** [comment]
Thanks @hoodriverheather! I used the Google Sheet in order to the latest-and-greatest for `Discipline` and `DataCategory`. While there, I also grabbed `Species`.

Two things:

- I think maybe Multiplex-Immunoflourescent Staining is misspelled? "flour" → "fluor"
- There's a box for "Method Details" on the form, but no `MethodDetails` on the Google Sheet; can we drop this box?
- The spreadsheet mentions a CDE `DOI URL` with a space in it; is that correct?

Woops, that three things 😅

Anyway, please see https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/metadata-collection-form/ for the latest.

**Comment by hoodriverheather** [comment]
@nutjob4life Thanks for catching all of these! 

- I fixed the typo for Multiplex-Immunofluorescent Staining. 
- We can leave Method Details off. We have decided now when working with investigators this is often better to capture at dataset level. 
- I also removed the space in the CDE DOIURL. :)

I realized after filling in the form the following:

- Make Discipline a check all that apply checkbox
- Can you add an other specify to DataCategory and allow them to enter something that isn't there?
- Do you think we should have a comments or questions section where they can ask us a question or provide more information about their metadata? This wouldn't become part of the .cfg but would be in the email. WDYT?

**Comment by nutjob4life** [comment]
Please check out the latest [dev form](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/metadata-collection-form/).

Next questions I have:

- [ ] Currently users must check at least one Discipline; is it okay to choose zero?
- [ ] Should it be linked to? If so, on what page?
- [ ] Should it require login to access? If not, I'll add a captcha
- [ ] If it requires login to access, is it just a general login requirement or do you have to be a member of a certain group?

**Comment by nutjob4life** [comment]
@hoodriverheather please check out the open questions ↑ when you get a chance 🙏

**Comment by hoodriverheather** [comment]
@nutjob4life here are answers to the above questions:

- Discipline can stay required b/c there's an Undefined option
- Can there be a link on the Data page? I know this wasn't an option in Plone. Just thinking it would be cool if users didn't see their data listed on the data page - they could fill out this form :) We should also ask Dan what he thinks.
- No login access. 
Thanks!

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this:

- [ ] Visit the [science data page](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/data/) and ensure there's a link to the metadata collection form
- [ ] Follow the link and ensure it ends up at the form
- [ ] Fill out the form and ensure it generates the appropriate email
- [ ] Ensure the captcha is there

**Comment by hoodriverheather** [comment]
@nutjob4life This is sooooo close. 

What about adding the following text to the science data page. If you have data you would like captured or linked in LabCAS, please complete the Metadata Collection Form. Or contact the Informatics Center with any questions.

I'm struggling with what to call the Reference URL and the Reference URL Description. Users never understand what this field is. How about:
Change the label of Reference URL to URL link and change the description to: Optional URL link to external or additional data described by this collection. WDYT?

**Comment by nutjob4life** [comment]
@hoodriverheather okay here's how the Data page could look:

<img width="788" alt="Screenshot 2023-03-14 at 5 10 40 PM" src="https://user-images.githubusercontent.com/814813/225154028-737de5b8-b258-48a3-80b2-ebe4acb67ca0.png">

That look all right? The "Informatics Center" is a `mailto:` link to `ic-portal@jpl.nasa.gov`.

For the form itself, I used your suggested text:

<img width="638" alt="Screenshot 2023-03-14 at 5 11 25 PM" src="https://user-images.githubusercontent.com/814813/225153967-cd419a6b-0551-4554-8769-ce4afed32183.png">

Does that look okay? Should the "Reference URL Description" change too?

**Comment by hoodriverheather** [comment]
@nutjob4life I think that looks great! Thanks!!

**Comment by nutjob4life** [comment]
@hoodriverheather okay, sending to edrn-dev

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this:

- [ ] Visit the [science data page](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/data/) and ensure there's a link to the metadata collection form—and that the text that talks about the form matches the expectation and includes email to the ic-portal address
- [ ] Follow the link and ensure it ends up at the form
- [ ] Ensure that the URL Link field and its help text are updated
- [ ] Fill out the form and ensure it generates the appropriate email
- [ ] Ensure the captcha is there

**Comment by hoodriverheather** [comment]
This looks great!! 🎉
