### ISSUE TITLE
Some biomarkers - page doesn't exist

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#24]
When clicking on some of the biomarkers on the biomarker tab I get a page doesn't exist error.
Examples:
https://edrn-aws.nci.nih.gov/biomarkers/ACTC1
https://edrn-aws.nci.nih.gov/biomarkers/ADIPOQ

**Comment by nutjob4life** [comment]
The issue was with some old RewriteRules that transitioned from the Apache HTTPD at the Shady Grove facility and into the Application Load Balancer (ALB) in AWS. CBIIT corrected the issue.
