### ISSUE TITLE
Resources tab - links broken

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#25]
From resources tab

- click on the secretome link - https://edrn.jpl.nasa.gov/secretome -  from the resources tab  it doesn’t seem to take me to the tool

- click on the miRNA link - https://edrn-aws.nci.nih.gov/microrna. Then click on dashboard link https://edrn.jpl.nasa.gov/miRNA/- I get page doesn’t exist

- click on specimen reference sets - https://edrn-aws.nci.nih.gov/resources/sample-reference-sets - click on  a reference set document - https://edrn-aws.nci.nih.gov/specimens/reference-sets/bbd-tissue-reference-set/bbd-reference-set-summary-document – page doesn’t exist

**Comment by nutjob4life** [comment]
OK, it looks like there are actually three separate issues here. One by one:

## Secretome

The Secretome tool was brought down and is archived as part of the [transition to cancer-new](https://github.com/orgs/EDRN/projects/7). I removed the link.

## miRNA

miRNA was also brought down as part of the [transition to cancer-new](https://github.com/orgs/EDRN/projects/7). Removed the link.


## Reference Sets

1. Visit Resources at https://edrn.nci.nih.gov/resources
2. Click "Specimen Reference Sets" which takes you to https://edrn.nci.nih.gov/resources/sample-reference-sets
3. Try following links here

I tried every link on this page and they all worked except

- BBD Refernce Set Summary Document
- SOP For Selection of Benign Breast Disease Project

I located these two files and uploaded and re-linked them.

**Comment by nutjob4life** [comment]
@hoodriverheather the JPL system administrators have revived the Secretome Tool, so I put the link back on https://edrn.nci.nih.gov/resources/secretome

As for the reference sets, you can the missing entries for "BBD Refernce Set Summary Document" and "SOP For Selection of Benign Breast Disease Project" on https://edrn.nci.nih.gov/resources/sample-reference-sets

**Comment by hoodriverheather** [comment]
Thanks for reviving these tools.
Everything is working great.
