### ISSUE TITLE
LabCAS public collection link on Protocol page takes you to login page in LabCAS

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#250]
## 🐛 Describe the Bug

From the Protocol page - https://edrn.nci.nih.gov/data-and-resources/protocols/447-an-automated-system-for-breast-cancer-biomarker-analysis/
click on the Data collections link, that is public. You are taken to the LabCAS login page instead of being taken directly to the collection in LabCAS.

**Comment by nutjob4life** [comment]
Hi @hoodriverheather! Thanks for doing this incredibly thorough testing.

This is definitely [a LabCAS bug](https://github.com/EDRN/labcas-ui/issues/170).

I tried it with Safari, Firefox, and Chrome and I was not prompted to log in once.
