### ISSUE TITLE
Upgrade to Django 4.2 and Wagtail 5

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#251]
Django 4.2 is out (as of April 3, we're on 4.1) and psycopg 3 has been out for a while (and we're still using 2) and we should upgrade P5 to use both.

👉 **Note:** The latest Wagtail, 4.2.2, does not support Django 4.2. Put this in the icebox for now.

UPDATE: Wagtail 5.0 is out and support Django 4.2

**Comment by nutjob4life** [comment]
I've reviewed [the release notes for Wagtail 5.0](https://docs.wagtail.org/en/stable/releases/5.0.html) and I'm thinking we should postpone upgrading at this time. In particular:

- We rely on wagtail-robots, wagtail-favicon, and wagtail-menus and these have not been updated for Wagtail 5. (In particular, wagtail-favicon still expects Wagtail 3 and upgrading to 5 will absolutely break it.)
- Searching (via Elasticsearch) does only full-word matches in Wagtail 5 which means "meth" would no longer find "methylation" without some perhaps wide-reaching code changes (autoindex fields and search view updates)

I certainly hope we won't get hit by any security updates by not upgrading to 5.0 at this point.

**Comment by nutjob4life** [comment]
One of the Django developers advises that we can

- Drop wagtail-robots and use https://adamj.eu/tech/2020/02/10/robots-txt/ instead
- Drop wagtail-favicon and use https://adamj.eu/tech/2022/01/18/how-to-add-a-favicon-to-your-django-site/ instead

And it looks like [wagtail-menus](https://github.com/jazzband/wagtailmenus) got updated so we might be able to do this!

[Elasticsearch changes](https://docs.wagtail.org/en/stable/releases/5.0.html#elasticsearch-backend-no-longer-performs-partial-matching-on-search) can also be accommodated if we change from `search` to `autocomplete`, which should be fairly easy.

**Comment by nutjob4life** [comment]
Upgrade underway, but noting:

- Still need to migrate from [ModelAdmin to Snippets](https://docs.wagtail.org/en/stable/reference/contrib/modeladmin/migrating_to_snippets.html)
- Still need to upgrade to Elasticsearch 8 in the Docker Composition (and in local dev)

**Comment by nutjob4life** [comment]
Elasticsearch 8.10.2 now in use in the Docker Composition

**Comment by nutjob4life** [comment]
ModelAdmin replaced with Snippets—at least for CDE management. The add-ons for WagtailMenus and WagtailRobots still require ModelAdmin so I've left it in for now.

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this, [visit the dev portal](https://edrn-dev.jpl.nasa.gov/portal/renaissance) and try _everything_. 

Upgrading to the app framework to Django-4.2.6 (up from 4.1.7), the search engine to Elasticsearch-8.10.2 (up from 7.17.10), and the CMS to Wagtail-5.1.3 (up from 4.2.0) was a major undertaking and has the potential to affect everything. 

But there were some high severity vulnerabilities that needed patching and now we're back in the safety zone!

**Comment by nutjob4life** [comment]
Le sigh. Wagtail 5.2 just came out. However, it supports OpenSearch, which is the recommended replacement to Elasticsearch which we are currently using. I'm thinking we should upgrade to 5.2.  Another notable feature is environmentally friendly image support (less data, less electricity, more green).

Reading through [the release notes](https://docs.wagtail.org/en/stable/releases/5.2.html) seems to suggest we won't have to make too many changes.

**Comment by nutjob4life** [comment]
EDRN Portal P5 now using Wagtail 5.2

**Comment by hoodriverheather** [comment]
@nutjob4life Looking good 🤞 I'm closing. Woot! Woot!

**Comment by nutjob4life** [comment]
![Woot woot!](https://github.com/EDRN/P5/assets/814813/4393f709-f688-4881-99b1-dc41b0e144a1)
