### ISSUE TITLE
CC the submitter of Specimen Reference Sets

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#255]
During the Bio-informatics Systems Planning meeting on 2023-04-13, Natalie requested that once the email is generated for specimen reference sets from the form that the submitter of the form get a copy so they have a "receipt" of their submission.

**Comment by nutjob4life** [comment]
While this works with JPL's email servers it doesn't with NCI's, so re-opening until we can figure this out

**Comment by nutjob4life** [comment]
Resolved this at NCI. The key: the "From:" address must be `noreply@nih.gov`.

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this:


### First, Do Not Disturb the DMCC

The first part of testing this is to configure the development form to _not_ send emails to the DMCC and to ensure that JPL can actually send the email. Here's what you'll need to do:

1. Visit https://edrn-dev.jpl.nasa.gov/portal/renaissance/admin/ and log in
2. From the "Pages >" menu in the left side bar, navigate through EDRN → Data and Resources → Specimen Reference Sets and click the ✏️ on Specimen Set Request Form
3. Scroll down and change the "Email: From Address" from `no-reply@nih.gov` to your own email address.
4. Delete `edrndmcc@fredhutch.org` from the "Email: To address", leaving only `sean.kelly@jpl.nasa.gov` and `heather.kincaid@jpl.nasa.gov`
5. Then, under "Submitter's Copy Email", change the "Submitter From" from `edrndmcc@fredhutch.org` to your own email address.
6. Click "Publish"


### Now, the Actual QC

1. After completing the above, you'll have a green bar at the top with a "View Live" button. Click it.
2. Fill in the form as required, except for "Email", use a personal email address, such as your Hotmail, AOL, Lycos, Mail.com, or Yahoo email address.
3. Submit the fomr
4. Ensure that your `heather.kincaid@jpl.nasa.gov` address receives the submitted form, and that your personal email receives a copy of the submitted data—but with different wording.

**Comment by hoodriverheather** [comment]
@nutjob4life Woot! Woot! I got a copy of the submission. Looks great!
Do you want me to change the emails back in the form?

**Comment by nutjob4life** [comment]
Thanks @hoodriverheather! No need to change things back; the nightly build takes care of that.
