### ISSUE TITLE
Add missing links to the specimen reference sets page

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#257]
On the specimen reference sets page, there are several reference sets that have no hyperlink, such as for MSA. When a hyperlink is unavailable, have it link to the protocol.

Note that the second liver reference set also has no hyperlink; it should link to the same page as the liver one above it.

**Comment by nutjob4life** [comment]
These edits were made live in production.

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this:

1. Visit https://edrn.nci.nih.gov/data-and-resources/specimen-reference-sets/ in production
2. Ensure "MSA/Bladder" is a valid link
3. Go back, then scroll down to the second "Liver 111" set; ensure that its hyperlink has the same destination as the "Liver 111" set above it

**Comment by hoodriverheather** [comment]
@nutjob4life I know i already asked about this, but the links for the all of reference sets except the last set listed "Panc Cyst" go to a page that has a link to a pdf documentation file and the application form [Application Form for EDRN Reference Sets](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/specimen-reference-sets/specimen-set-request-form/)
Would it be OK if i confirm with Jackie to make sure we want the Panc Cyst words to link to the protocol page?

**Comment by nutjob4life** [comment]
Confirm away! I'll re-open this issue until we hear back.

**Comment by nutjob4life** [comment]
JD said:

> There isn’t a PDF for Panc Cyst, so linking to Protocol Page is fine.

So that's that!
