### ISSUE TITLE
Dataset metadata form

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#260]
## 🤔 Tell Us About the Feature

Lose wireframe:
https://app.diagrams.net/#G1P7zvvPydbZ08-epAvsg_vZUL0Wgz_AwS

Use the instructions and formats where applicable from the Collection Metadata form.

**Comment by nutjob4life** [comment]
@hoodriverheather right now I have this develop just a plain email which shows each field and the value. Do you want a `.cfg` file instead like for the collection-level form?

**Comment by nutjob4life** [comment]
@hoodriverheather I don't have access to KSDB. Could you tell me what the permissible values are for "specimen type"? Or should this be a fill-in-the-blank field? Multi-line field?

Also: what fields are required and which are optional?

**Comment by hoodriverheather** [comment]
> @hoodriverheather right now I'm developing this with a plain email which shows each field and its matching value. Do you want a `.cfg` file instead like for the collection-level form?

@nutjob4life A .cfg file would be great!

**Comment by hoodriverheather** [comment]
> @hoodriverheather I don't have access to KSDB. Could you tell me what the permissible values are for "specimen type"? Or should this be a fill-in-the-blank field? Multi-line field?
> 
> Also: what fields are required and which are optional?
For specimentype, it could be a pick all that apply. One of the items is NA.

https://mcl.jpl.nasa.gov/ksdb/view/ 
i'll send you the username/password. you need to be on VPN.

Dataset doesn't have many required fields. Just DatasetName and Dataset Description. A lot of the dataset metadata can populate up or down from the collection or the file metadata.

**Comment by nutjob4life** [comment]
@hoodriverheather a [first draft of the form](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/cde/labcas-metadata-and-common-data-elements/dataset-metadata-form/) is available to try out.

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this:

1. Visit https://edrn-dev.jpl.nasa.gov/portal/renaissance/
2. From the menu, choose "EDRN Common Data Elements (CDEs)"
3. Click "LabCAS Metadata and Common Data Elements"
4. Scroll down, then click "Dataset Metadata Form"
5. Fill in the various required boxes and as many optional boxes as you like
6. Complete the CAPTCHA
7. Click "Submit"
8. Ensure you receive an email with a draft `.cfg` file filled in with the values from your form

**Comment by hoodriverheather** [comment]
@nutjob4life Can you add "Not Applicable" to the Assay pick list? Also, Content type permissible value should be: Clinical
Biospecimen
SOP
Documentation
Instrument Output
Metadata
Ancillary Data
Summary

**Comment by nutjob4life** [comment]
@hoodriverheather consider it done!

https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/cde/labcas-metadata-and-common-data-elements/dataset-metadata-form/

**Comment by hoodriverheather** [comment]
@nutjob4life Thanks!
