### ISSUE TITLE
Broken PDF Link

### ISSUE THREAD

**Issue by askarlupka** [EDRN/P5#263]
## 🐛 Describe the Bug

Link to protocol PDF is broken. 

## 📜 How To Reproduce

Put steps to reproduce the behavior here, **including URLs**, such as
1. Go to https://edrn.nci.nih.gov/data-and-resources/specimen-reference-sets/ovarian-breast-cancer-reference-sets/
2. Click on Biomarker Reference Sets for Cancers in Women (BRSCW)](http://localhost:6468/documents/38/BRSCW_final1_2-6-07LF.pdf
3. Receive the error of 'Problem loading page'
![image](https://user-images.githubusercontent.com/54122306/235736649-35925ba3-f5c6-4afe-9c6f-b4e836fdfbd8.png)

❗️ Mention if the bug appears if you're logged in or not—or possibly *all* the time!
Occurs when either logged in or not

## 🔎 Expected Behavior

I was expecting a pdf of the protocol description

**Comment by nutjob4life** [comment]
Thanks for your report @askarlupka. The page link has been corrected.

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this:

1. Visit https://edrn.nci.nih.gov/data-and-resources/specimen-reference-sets/ovarian-breast-cancer-reference-sets/
2. Click "Biomarker Reference Sets for Cancers in Women (BRSCW)" and ensure you get a PDF file, not an error
