### ISSUE TITLE
Collection Metadata Form Update

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#264]
@nutjob4life WDYT about this text?

<img width="944" alt="Screenshot 2023-04-19 at 2 02 30 PM" src="https://user-images.githubusercontent.com/58526347/236036574-890b168d-eb23-465d-87cc-e89918ca1e5f.png">

**Comment by nutjob4life** [comment]
Done. See it live at:  https://edrn.nci.nih.gov/data-and-resources/metadata-collection-form/

**Comment by hoodriverheather** [comment]
Awesome!
