### ISSUE TITLE
LabCAS API page

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#265]
## 🤔 Tell Us About the Feature

Rather than host the LabCAS API documentation and associated files on industry-discoverable platforms, we want them _not on LabCAs_ but on the EDRN portal—and to require login with your EDRN credentials to see it.

## 🎇 What Solution You'd Like

We don't want this on LabCAS. We want it on the portal.

## 〽️ Alternative Ideas

NIST is going to put them on LabCAS, so maybe EDRN should too? Whatever!

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this:

1. Ensure you're logged out
2. Visit https://edrn-dev.jpl.nasa.gov/portal/renaissance
3. From the Data and Resources menu, choose "EDRN Common Data Elements (CDEs)"
4. Click "LabCAS Metadata and Common Data Elements"
5. Scroll to the bottom and click "LabCAS API"
6. Ensure you're prompted to log in
7. Log in
8. Ensure you can read the documentation. Try the tabs to swap between "Curl" and "HTTP" endpoints
9. Ensure you can download the Postman and OpenAPI documentation specifications via the two buttons at the top

**Comment by hoodriverheather** [comment]
@nutjob4life It looks great. I agree it should be on LabCAS. WDYT about LabCAS at least linking to this from the help pages? @yuliujpl Would you either add this to the help pages, password restricted. Or link to the Portal? This is the doc that can be posted to the NIST LabCAS :)

**Comment by nutjob4life** [comment]
You're lucky I like _deleting_ code!

If LabCAS should host this documentation and API specifications, I'll delete the portal support for serving this 😆

**Comment by hoodriverheather** [comment]
@nutjob4life Thanks Sean! I don't want you to have to delete code :(
