### ISSUE TITLE
CDE Explorer

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#269]
Create a tree-based explorer with collapsible sections and detail views for the Common Data Elements.

In the Portal, this will must strictly be a tree-based display due to Section 508 requirements. (LabCAS UI falls under the scientific data application exception and can "go wild" with graphs.)

The tree diagram should have a two-part display (side-to-side on desktop, top-top-bottom on mobile):

1. The left (top) part should display the interactive tree. Each node in the tree should represent an entity (object) in the data model, such as a collection, dataset, core file, etc.
2. The right (bottom) part should display details about the currently selected (clicked or tapped) node.

Bonus points for being able to download the model in some portable format.

**Comment by nutjob4life** [comment]
@hoodriverheather couple questions I need help with:

1. Would you prefer to curate CDEs in Google Sheets or do you want a "CDE Composer" built into the portal—made from Wagtail CMS's admin interface?
2. What are the attributes of each data element (name, description, data type, permissible values, min max values, default values, inherited from a "parent" entity, required or optional, etc.)

**Comment by nutjob4life** [comment]
@hoodriverheather could you provide some feedback [on the above](https://github.com/EDRN/P5/issues/269#issuecomment-1599016253)?

**Comment by nutjob4life** [comment]
Met  on 2023-07-12 to discuss; Summary:

- We're sticking with the simplified tree view (attributes not in the tree)
- Google sheets are the _de facto_ gold standard for now
- The attributes are on the columns of the sheet

**Comment by nutjob4life** [comment]
Based on a meeting with @hoodriverheather on 2023-08-09, we want to indicate those CDEs whose values can be inherited from other objects, so opening this back up for now.

**Comment by nutjob4life** [comment]
Implemented the latest request for change: items with the "inheritance" checkbox checked in the [spreadsheet](https://docs.google.com/spreadsheets/d/1PAVUvmi0J-j6fK5dpltRIW8vRzVjh4kzpNReGFOQIe4/) now get special display on the attribute buttons and on the attribute canvas after an attribute button is clicked. [See it live](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/cde/edrn-data-model/).

@hoodriverheather to QC this, [follow these instructions](https://github.com/EDRN/P5/issues/269#issuecomment-1664097088) but also add a 7th step to check for inheritance attributes.

**Comment by hoodriverheather** [comment]
@nutjob4life A few questions: are we ready to release this to the public? I think we should confirm with Dan. Do we want to wait until some of the biomarker model is cleaned up? Do we want to do any harmonization? Also, if we release, we should update the readme.

A few suggested page edits - 
<img width="1196" alt="Screenshot 2023-08-15 at 4 24 41 PM" src="https://github.com/EDRN/P5/assets/58526347/7d0b136a-c126-4f30-8ce8-8b5eb7bc7062">

**Comment by nutjob4life** [comment]
@hoodriverheather we can make this page private for now.

Also the labels "Biomarker Data Commons", "Biomarker Study Data", and "Biomarker Database" all come right from @dcrichto1 so I'm hesitant to make any changes. However, these are all editable in [the spreadsheet](https://docs.google.com/spreadsheets/d/1PAVUvmi0J-j6fK5dpltRIW8vRzVjh4kzpNReGFOQIe4/edit?usp=sharing) so we can make changes at any time.

**Comment by hoodriverheather** [comment]
@nutjob4life Sounds great. Thanks Sean.

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this, visit [data model](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/cde/edrn-data-model/) (logging in) and ensure it's all copacetic.

**Comment by hoodriverheather** [comment]
@nutjob4life Looks great!
