### ISSUE TITLE
Binary files in Specimen Ref Set Req Form are Base-64 encoded

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#272]
## 🐛 Describe the Bug

Binary files uploaded via https://edrn.nci.nih.gov/data-and-resources/specimen-reference-sets/specimen-set-request-form/ are emailed as base-64 encoded. They should be usable directly from your email reader and not require a decoding step.

**Comment by nutjob4life** [comment]
Fixed in c8d8a04627f885c1f8bf5ba80489152991e05743

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this:

1. First, change the form settings so it doesn't bother the DMCC
2. Then, submit the form with a binary file (PDF, JPEG, PNG, etc.) as the "proposal"
3. Finally, wait for emails

The following subsections detail how to do these three steps.

### DMCC Annoyance Avoidance

To prevent the DMCC from receiving test email messages from the form, do the following:

1. Visit https://edrn-dev.jpl.nasa.gov/portal/renaissance/_util/login/?next=/portal/renaissance/ and log in with Super User credentials to the dev portal
2. Go to the [application form](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/specimen-reference-sets/specimen-set-request-form/)
3. Click the "NIH" badge in the lower right corner and choose "Edit this Page"
4. Scroll down to the Email section and change:
    - From address to your `heather.kincaid@jpl.nasa.gov`
    - To address also to `heather.kincaid@jpl.nasa.gov`
5. Scroll down to Submitter's Copy Email and change "Submitter from" to `heather.kincaid@jpl.nasa.gov`
6. At the bottom, click "Publish"
7. Click "View Live" to view the form

You don't have to change these back since this is a dev system and it gets automatically rebuilt every night anyway, overwriting your values.

### Submit the Form with a Binary Proposal File

After making the changes above, fill out the form:

1. Fill in any value you like for every field, except for `Email`, enter your Caltech email address, `hkincaid@jpl.caltech.edu`
2. For "Scientific Proposal", make sure you attach a binary file, not a plain `.txt` file. For example, a PDF, an image (JPEG, PNG, etc.), random data from `/dev/urandom`, Microsoft Word, etc., is fine.
3. Click Submit

### Wait for the Emails

It may take 5 to 10 minutes for the two emails to appear. You should receive:

- An email to `heather.kincaid@jpl.nasa.gov` with the specimen reference request
- An email to `hkincaid@jpl.caltech.edu` with a copy of the request as a receipt for the submitter

The emails can and probably will end up marked as "junk" because of the stringent policies of JPL's mail servers when handling email from automated processes (don't worry, NCI is much more lax).

Check:

1. Do both emails have attachments?
2. Can you open the attachments in both emails? For example, if you used a PDF, can you open the attachment with Preview.app?

If this all checks out, consider this QC'd. (I tested this end-to-end at https://edrn-dev.nci.nih.gov/ as well. Worked even better because the emails were not marked as junk!)

**Comment by hoodriverheather** [comment]
@nutjob4life Works great!

**Comment by nutjob4life** [comment]
![relief!](https://github.com/EDRN/P5/assets/814813/26fbed0b-db37-42ed-8ea9-0d2278f31f90)
