### ISSUE TITLE
P5 Slow

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#28]
Some things seem really slow on P5.– Going from list of members and clicked on JPL - https://edrn.nci.nih.gov/sites/128-nasa-jet-propulsion-laboratory – took forever.

**Comment by nutjob4life** [comment]
Some ideas:
-   Use the "sprite" image idea for the Quick Links portlet
    -   Or make Quick Links text-only
-   Have a local LDAP server in "replication" mode
    -   With authentication fallback to edrn.jpl.nasa.gov or cache successful credentials
-   Increase ZServer threads even more, 2→8→more

**Comment by nutjob4life** [comment]
With the Kara-blessed look/feel we've dropped the QuickLinks portlet which slowed things down considerably.
