### ISSUE TITLE
Display new DMCC data regarding data sharing and investigator interests

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#284]
The [Cancer Data Expo](https://github.com/EDRN/CancerDataExpo) recently gained support for two new kinds of data:

- [Data Sharing agreement date](https://github.com/EDRN/CancerDataExpo/issues/23)
- [Interest areas for investigators[(https://github.com/EDRN/CancerDataExpo/issues/22)

We should display these new data in the portal.

**Comment by nutjob4life** [comment]
@hoodriverheather  to QC this

1. Visit a site that has a data sharing policy date/time, such as [this site](https://edrn-dev.jpl.nasa.gov/portal/renaissance/about-edrn/sites/611-national-institute-of-standards-technology/), and ensure the data sharing policy date/time appears.
2. Visit a site that doesn't have a data sharing policy date/time, such as [this site](https://edrn-dev.jpl.nasa.gov/portal/renaissance/about-edrn/sites/710-carle-cancer-center/) and ensure no data sharing policy date/time appears.
3. Visit a person that has interests, such as [this one](https://edrn-dev.jpl.nasa.gov/portal/renaissance/about-edrn/sites/611-national-institute-of-standards-technology/locascio-laurie/), and ensure interest names and descriptions appear
4. Visit a person that has no interests at all, such as [this one](https://edrn-dev.jpl.nasa.gov/portal/renaissance/about-edrn/sites/128-nasa-jet-propulsion-laboratory/crichton-dan/)

Also let me know if there are any formatting changes you'd like to see.

**Comment by hoodriverheather** [comment]
@nutjob4life This is looking good. Poor Dan has no research interests :)
What about also creating a page that shows the Data Sharing Policy Status? It could list all sites, Date Policy Completed so that Natalie, etc. can see at a glance what sites haven't completed this task?

**Comment by hoodriverheather** [comment]
It looks like sites without a signed Data Sharing Agreement list seems really long. Only sites for the current 5 year round should be on this list.
Also, the title could be EDRN External Data Sharing and Reuse Policy Funding Cycle V. The heading for each list could be Sites with signed Data Sharing Policies
Sites pending signed Data Sharing Policies

Or something like that?
Thanks! HK

**Comment by nutjob4life** [comment]
Hi @hoodriverheather I'm not sure how to filter this list based on current 5-year round funding given the information that the DMCC provides in the RDF. The DMCC provides details on 335 sites.

- Is it member type? We could filter on the values Associate Member A - EDRN Funded, Associate Member B, Associate Member C, Biomarker Characterization Center, Biomarker Developmental Laboratories, Biomarker Reference Laboratories, Clinical Validation Center, Data Management and Coordinating Center, Informatics Center, National Cancer Institute, Non-EDRN Site, SPOREs. For example, we could exclude 127 Associate Member C and 58 associate Member B sites.
- Is it funding end date? We could exclude based on sites whose funding end date is blank in the RDF. There are 204 sites with blank end dates. Maybe that's better?

Let me know what sounds more correct.

**Comment by hoodriverheather** [comment]
@nutjob4life i think it's any site that has a MemberType=BCC, BDL, CVC, BRL. Not sure about DMCC. I will confirm with Jackie.

**Comment by hoodriverheather** [comment]
@nutjob4life confirmed. use member type as stated above and include DMCC. 
Do you think this could be included in this release?

**Comment by nutjob4life** [comment]
@hoodriverheather to complete QC on this, [in addition to these steps](https://github.com/EDRN/P5/issues/284#issuecomment-1708793121), also try the following:

1. Visit https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-sharing 
2. Ensure the title is "EDRN External Data Sharing and Reuse Policy Funding Cycle Ⅴ"
3. Ensure the next heading is "Sites With Signed Data Sharing Policies"
4. Ensure the number of such sites is above 40
5. After clicking through to a few, ensure they have data sharing policy date/times
6. Ensure the next heading is "Sites Pending Signed Data Sharing Policies"
7. Ensure the number of such sites is 30 or below
8. After clicking through to a few, ensure they do not have data sharing policy date/times
9. Click Log in and log in as a Super User
10. Click the NIH badge and choose Go to Wagtail Admin
11. Click Settings in the left, then click Informatics in the sub-menu that appears (you may have to scroll down)
12. Scroll down to Funding Cycle and change the cycle from Ⅴ to something else, then click save
13. Go back to https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-sharing and ensure the cycle № has changed

**Comment by hoodriverheather** [comment]
Perfect!! TY!

**Comment by hoodriverheather** [comment]
@nutjob4life btw - how do i navigate to this page rn? i wonder if we should ask Dan 😳

**Comment by nutjob4life** [comment]
@hoodriverheather for now the only way to get to it is if you know the link, which I think is fine. We can share it with Natalie or the DMCC as needed.
