### ISSUE TITLE
Change submission preamble on Data index page

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#285]
According to [this doc](https://docs.google.com/document/d/1MQHknaO5Q0S7wB_TA8EmaDGx48jJc1cvGQDGFKCA3l4/edit) @hoodriverheather would like the preamble on the [Data](https://edrn.nci.nih.gov/data-and-resources/data/) page changed.

The right way to do this is to no-longer hard-code that text in the page template, but make it an editable rich text field so that we can change it at whim, including links to other parts of the site, external links, email links, etc.

**Comment by hoodriverheather** [comment]
@nutjob4life This works perfectly!
Thanks so much!

**Comment by nutjob4life** [comment]
@hoodriverheather Thanks for the quick confirmation!
