### ISSUE TITLE
Committees and collab groups show their documents in not a great order

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#286]
When you visit a committee or a collaborative group page, such as the [Data Sharing and Informatics Subcommittee](https://edrn.nci.nih.gov/about-edrn/groups/data-sharing-and-informatics-subcommittee/), the "Documents" that belong to that group are shown in order of `last_published_at` ascending, which puts the newest stuff at the bottom.

Wagtail keeps the notion of sort order within a folder and lets you manually set the order that makes the most sense to you. But this `last_published_at` ascending destroys that. It'd be nice if each committee could chose the order of their documents.

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this, first read the comment above 👆. The idea is to not reinvent the wheel but use the content management features already in Wagtail—including ordering of items under a page. Thankfully Royce is already familiar with this—and now you will be too 😇

1. Visit https://edrn-dev.jpl.nasa.gov/portal/renaissance/ and click "Log in" and log in.
2. Then go to https://edrn-dev.jpl.nasa.gov/portal/renaissance/about-edrn/groups/data-sharing-and-informatics-subcommittee/ and notice the items under Documents: Data Sharing and Informatics Subcommittee Responsibilities - DRAFT, EDRN External Data Sharing and Reuse Policy Funding Cycle V, Archive, DMS Policy Resources
3. Now click the NIH badge in the corner and click Edit this page
4. Click the 3 horizontal dots at the top and click "Sort menu order". If you get a warning about leaving the page, leave the page anyway
5. Using the ⠿ controls on the left, try dragging some items around. For, example, you might put Archive last, maybe move EDRN External Data Sharing and Reuse Policy Funding Cycle V first, whatever!
6. In the upper right, click the "👁️ LIVE" button.
7. Confirm that the order of documents matches what you selected in step 5.

Note: you may have noticed that there are 4 documents but on step 5 there are 5 items appearing. That's because one of the items is a "Committee Event" item, and such items don't count as documents. They don't affect the sort order.

**Comment by hoodriverheather** [comment]
@nutjob4life Very cool! Thanks :)
