### ISSUE TITLE
Enable support for government shutdown banners

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#288]
Via Kara Smigel:

> If Congress doesn’t pass a budget package or establish a Continuing Resolution by 11:59 p.m. on Saturday, September 30, shutdown plans will be initiated on Monday, Oct. 2. No action should be taken on Sunday, October 1. 

On October 2, the following banner should be placed:

> Because of a lapse in government funding, the information on this website may not be up to date, transactions submitted via the website may not be processed, and the agency may not be able to respond to inquiries until appropriations are enacted.
> 
> The NIH Clinical Center (the research hospital of NIH) is open. For more details about its operating status, please visit [cc.nih.gov](https://cc.nih.gov/).
> 
> Updates regarding government operating status and resumption of normal operations can be found at [OPM.gov](https://www.opm.gov/).

**Comment by nutjob4life** [comment]
Ugh, we are not set up for having a site-wide banner like this. However, neither is the Home Page content model either, which allows just three things:

- A "title" block (an `<h1>`)
- A carousel
- Site section cards

The best we can do _ad hoc_ is to replace the current carousel with a new carousel that has the shutdown message.

However, only plain text is allowed here, so we can't hyperlink. Also, the caption text is limited in length, so we'll need two images (they can be the same) in the carousel to hold part of the complete shutdown message.

And we'll need to save the original carousel, which is as follows:

1. Image = "Emblematic image of the Early Detection Research Network featuring a cell background", label = "The Early Detection Research Network", caption = "Stimulating collaborative discovery, development, and validation of biomarkers for cancer risk and early detection."
2. Image = "Emblematic image of the Early Detection Research Network featuring a bone-cancer background", label = "Biomarkers", caption = "The key to early detection."
3. Image = "Emblematic image of the Early Detection Research Network featuring a biosensor background", label = "Over 1600 Biomarkers", caption = "More biomarker research means earlier detection—which results in better patient outcomes."

**Comment by nutjob4life** [comment]
Possible shutdown banner image attached
![shutdown](https://github.com/EDRN/P5/assets/814813/f13a7619-8572-4657-b3a9-28980ce35cd0)

**Comment by nutjob4life** [comment]
Looks like we dodged a shutdown for now; however for the "next time" (and there will be a next time—thanks dysfunctional government!) we should accommodate site-wide banners.

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this:

1. Visit https://edrn-dev.jpl.nasa.gov/portal/renaissance and notice there is no banner (aside from our "development notice", which is separate)
2. Log in as a super user
3. Click the NIH badge in the lower right and choose "Go to Wagtail Admin"
4. In left menu bar, click Settings → Informatics
5. Scroll down to "Site wide banner" and enter some text, then click Save
6. Return to https://edrn-dev.jpl.nasa.gov/portal/renaissance and ensure your text appears
7. Navigate to other pages on the site and ensure your text appears
8. Return to the Wagtail Admin → Settings → Informatics and delete the text in "Site wide banner"
9. Return to https://edrn-dev.jpl.nasa.gov/portal/renaissance and ensure your banner is gone

**Comment by hoodriverheather** [comment]
@nutjob4life This works well! Should we include in this release?

**Comment by nutjob4life** [comment]
Yep Already included in the [6.6 Milestone](https://github.com/EDRN/P5/milestone/26?closed=1).
