### ISSUE TITLE
On vanity page, add data collection lists

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#289]
In the list of data collections, note the relationship the person has to the data—whether they're PI, co-PI, co-I, I, or involved I.

And also correct the open/closed protocol tables to change "Datasets" to "Public Data Collections"

**Comment by hoodriverheather** [comment]
@nutjob4life These changes all work. I just have a question about why we are only showing public collections on this page. There are both public and private collections shown on the Data page and the protocols. For example, https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/protocols/121-standard-specimen-reference-set-breast-cancer-and-imaging/ shows private collections. Should we just show all collections?

**Comment by nutjob4life** [comment]
Hi @hoodriverheather I'm not sure why we wanted just public. I've modified it to do public and non-public. To QC this revision:

1. Visit the protocol [Standard Specimen Reference Set: Breast Cancer and Imaging](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/protocols/121-standard-specimen-reference-set-breast-cancer-and-imaging/)
2. Scroll down and note there are 3 data collections. You can follow the link to each to ensure they're all non-public
3. Scroll back up and click "Marks, Jeffrey"
4. Look for Open Protocols
5. Note that the table heading changed from "Public Data Collections" → "Data Collections" 
6. Scroll down and look for "Standard Specimen Reference Set: Breast Cancer and Imaging"
7. Note that there are 3 data collections, which matches the number in step ②

**Comment by hoodriverheather** [comment]
@nutjob4life This looks great, but we should confirm with Dan to make sure it's ok to show private data on public portal.

**Comment by nutjob4life** [comment]
@hoodriverheather fair enough; let's keep the issue open until we can get confirmation. Could you put this onto our 2023-11-07 agenda?

**Comment by nutjob4life** [comment]
@hoodriverheather I think we can close this issue now, especially given the fixes addressed [in this issue](https://github.com/EDRN/P5/issues/298), right?
