### ISSUE TITLE
CBIIT requests that we automate the cbiit-deploy script and docker-compose.yaml

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#291]
Based on the recent 6.5 staging tier debacle, I learned that part of the problems we're facing is that the teams that manage cloud deployments and the teams that manage infrastructure have been separated. While Jenkins is shared by both teams to automate the deployments of websites to the three tiers (dev, stage, prod), they aren't allowed to alter the Jenkins configurations to make that possible. The other team is allowed to alter Jenkins configurations, but can't run deployments.

One way out of this mess is to no longer require Jenkins changes for each Portal release. CBIIT insiders (Cuong Nguyen, namely) informed me that if I could find a way to automate updating the `cbiit-deploy` scripts and `docker-compose.yaml` files, it would go long way towards speeding up future releases.

**Comment by nutjob4life** [comment]
Currently testing this with CBIIT Jenkins and https://edrn-dev.nci.nih.gov/

**Comment by hoodriverheather** [comment]
@nutjob4life I don't think there's a way to test, which if fine. :) I'm going to close.

**Comment by nutjob4life** [comment]
Thanks @hoodriverheather !
