### ISSUE TITLE
Minor update to Biomarkers Non-public biomarker message

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#294]
Is it possible to add a link to login in the message that appears throughout the Biomarker pages "tabs":
Non-Public Biomarker
Organ-specific information for some biomarkers are currently being annotated or are "under review". Logging in may give you privileges to view additional information. Contact the [Informatics Center](mailto:ic-portal@jpl.nasa.gov) if you believe you should have access.

To add a hyperlink to the logging that takes users to the login page?
<img width="1119" alt="Screenshot 2023-11-02 at 9 55 01 AM" src="https://github.com/EDRN/P5/assets/58526347/2f3b7a4c-b0b6-4142-a56e-6062ff271dc8">

**Comment by nutjob4life** [comment]
Hi @hoodriverheather this is possible, but I'd have to move it [from here where you can edit it](https://edrn.nci.nih.gov/admin/snippets/edrnsitecontent/boilerplatesnippet/) to software so I can generate the appropriate login link with `next` parameter to take you back to the biomarker.

That means that if you ever want to change the wording, it'd have to wait for the next software release.

Is that okay?

And if so, do you also want a login hyperlink for the words "logging in" at the [bottom of this page](https://edrn.nci.nih.gov/data-and-resources/biomarkers/)?

**Comment by hoodriverheather** [comment]
@nutjob4life I don't want to make it too difficult. So, we can leave for now if you want. It was just a suggestion.
WDYT?

**Comment by nutjob4life** [comment]
Implemented for individual biomarkers and for the biomarker index page.

**Comment by hoodriverheather** [comment]
@nutjob4life Thanks! Looks great!
