### ISSUE TITLE
Searching for CA125 on Portal Search returned no results

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#295]
## 🐛 Describe the Bug

I entered "CA125" into the top right search text box (in line with menu). No results was returned.
<img width="1172" alt="Screenshot 2023-11-02 at 3 53 55 PM" src="https://github.com/EDRN/P5/assets/58526347/141c5bba-66e3-4c54-8b3b-d7c92c631517">

It does work if you search on the Biomarker Tab.

**Comment by nutjob4life** [comment]
Thank you thank you thank you! Excellent catch.

I've pushed a fix and rebuilt the [dev portal](https://edrn-dev.jpl.nasa.gov/portal/renaissance). Give it a try?

**Comment by hoodriverheather** [comment]
@nutjob4life Works great! I'm going to close 👍
