### ISSUE TITLE
Publications are being shown that are way before the year 2000

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#300]
## 🐛 Describe the Bug
https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/publications/

Publications are being shown that are way before the year 2000.

**Comment by nutjob4life** [comment]
@hoodriverheather maybe you should verify this with the DMCC? The publications in their SOAP XML API have the following:

- From the year 1975: 47732, 1237467
- From the year 1977: 73325
- From the year 1979: 35531
- From the year 1980: 7001478
- From the year 1983: 6310399, 16453457
- From the year 1984: 6147198, 6383854, 6201741, 6203516
- From the year 1985: 2410004, 2874483
- From the year 1986: 2947337
- From the year 1987 … 6 pubs
- From the year 1988 … 3 pubs
- And so forth and so on

Note that pub 2410004 is from 1985 but is titled "CA19-9 as a marker for ovarian cancer: alone and in comparison with CA125", so it seems relevant.

**Comment by nutjob4life** [comment]
@hoodriverheather in case it helps, here's a report of all pubs we get from the DMCC prior to the year 2000: [old-pubs.csv](https://github.com/EDRN/P5/files/13312796/old-pubs.csv)

This issue isn't on the 6.7 milestone yet. Should it be? We can manually filter out older pubs, but as I noticed, many of the titles do mention biomarkers.

**Comment by hoodriverheather** [comment]
@nutjob4life UGH! Thanks! I wonder if we should draft a general email to DMCC asking about this, the HTML characters in both the Vanity pages and the <br> in Protocols. I also just noticed that the Reference Set WG doesn't have any people https://edrn-dev.jpl.nasa.gov/portal/renaissance/about-edrn/groups/reference-set-working-group/ 🙃
WDYT?

**Comment by nutjob4life** [comment]
@hoodriverheather I'm not sure; it might be easier just to continue to have our own code clean up after theirs. We already filtering out bad PubMed IDs, bad email addresses, bad markup in certain areas.

As for the Reference Set Working Group, it looks like it no longer appears in their SOAP XML API. In fact, [on this page](https://www.compass.fhcrc.org/edrns/cgi-bin/committee/commi.asp?p=committee), none of the three bottom working groups appear.

I can delete them from the production portal if they're no longer relevant.

**Comment by hoodriverheather** [comment]
@nutjob4life I guess I should check w Jackie.

**Comment by hoodriverheather** [comment]
@nutjob4life so, the bottom 3 Working Groups on the DMCC portal are not showing up in the SOAP XML API? I know there's a stat wg that's active, so that may be an error on their side.

**Comment by hoodriverheather** [comment]
<img width="828" alt="Screenshot 2023-11-09 at 4 07 07 PM" src="https://github.com/EDRN/P5/assets/58526347/a91d27db-f465-475c-924b-288bb1d34b0d">

**Comment by nutjob4life** [comment]
@hoodriverheather correct, none of these appear in the SOAP API anymore:

- Standing Review Group
- Statistical Working Group
- Reference Set Working Group

**Comment by nutjob4life** [comment]
It's always fun when we get weird data! 😝

Refocusing this issue back onto publications before the year 2000, could you share the spreadsheet [linked in this comment](https://github.com/EDRN/P5/issues/300#issuecomment-1804684162), `old-pubs.csv`, with the DMCC? They can address if these publications are relevant or clean up some mistyped PubMed IDs.

Meanwhile, let me know if you'd like the portal to not display any publications from before 2000 regardless of what the DMCC sends us.

**Comment by hoodriverheather** [comment]
@nutjob4life I'm drafting an email, but wanted to confirm one question before I send - are these from DMCC not BMDB? Correct?

**Comment by nutjob4life** [comment]
@hoodriverheather looks like 26 of them come from BMDB. I've created a new csv file, [old-pubs-no-bmdb.csv](https://github.com/EDRN/P5/files/13356108/old-pubs-no-bmdb.csv), that contains publications from before the year 2000 that come solely from the DMCC.

**Comment by nutjob4life** [comment]
@hoodriverheather closing this as it seems to be in the DMCC's bailiwick.
