### ISSUE TITLE
"nan" shows up in Data Model Viewer when clicking on Biomarker Data Models

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#301]
## 📕 Summary

When you visit [the data model viewer](https://edrn.nci.nih.gov/data-and-resources/cde/edrn-data-model/) and you click on "Biomarker Data Models", the right-side panel shows `nan`.

<img width="767" alt="Screenshot 2023-11-09 at 12 18 23 PM" src="https://github.com/EDRN/P5/assets/814813/0440f805-e12e-48b4-85b3-f02079163fb6">

## 🔍 Details

The [spreadsheet](https://docs.google.com/spreadsheets/d/1PAVUvmi0J-j6fK5dpltRIW8vRzVjh4kzpNReGFOQIe4/) that provides this data should be updated via the following:

1. Open [the spreadsheet](https://docs.google.com/spreadsheets/d/1PAVUvmi0J-j6fK5dpltRIW8vRzVjh4kzpNReGFOQIe4/)
2. At the bottom, click the "Structure" tab
3. Fill in text for cell C17 (and optionally cell D17)
4. Return to [the data model viewer](https://edrn.nci.nih.gov/data-and-resources/cde/edrn-data-model/) as a super user and click "Update from Google Drive"
5. Once it's done, click "View Update Log" and check for any errors
6. If there are no errors, click "Biomarker Data Models" and ensure your text appears

**Comment by nutjob4life** [comment]
@hoodriverheather could you take another look at this? At least for me, [the spreadsheet](https://docs.google.com/spreadsheets/d/1PAVUvmi0J-j6fK5dpltRIW8vRzVjh4kzpNReGFOQIe4/) still has blank cells in C17 and D17.

**Comment by hoodriverheather** [comment]
@nutjob4life Oh - sorry I missed that! I put some text in, feel free to edit!

**Comment by nutjob4life** [comment]
@hoodriverheather no worries! And feel free to edit? I had no idea what to put in there—that's why I assigned the issue to you! 😝

Anyway, the "nan" is gone so closing this. Thank you! 🙏
