### ISSUE TITLE
Member Finder issue/enhancement

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#302]
## 🐛 Describe the Bug

When i go to the member finder and enter a name, I get the number of matches and can see the list of people, but I can't click on any to see the details such as contact info, etc.
https://edrn-dev.jpl.nasa.gov/portal/renaissance/find-members#pi=Li%2C%20Christopher
<img width="1214" alt="Screenshot 2023-11-10 at 11 20 31 AM" src="https://github.com/EDRN/P5/assets/58526347/cfc26420-6c7b-4377-81fd-7a1fbae5e0e8">

I think the member finder should allow you to click on the person or site to see the detailed information.

Also, should we add member finder to the drop down menu? It's currently only available from the home page "box".

**Comment by nutjob4life** [comment]
@hoodriverheather works for me.

Ohhhhh wait—I'm clicking on the photo/silhouette. Not the name. I'll hyperlink the name.

As for putting the member finder on the navigation menu, [see this issue](https://github.com/EDRN/P5/issues/213). If you want it for 6.7, go ahead and re-open _that_ issue and assign it the 6.7 milestone. We've got one week before code freeze! 🥶

Currently you can get to the member finder from three places:

- [Home page](https://edrn.nci.nih.gov), in the "Work with EDRN" box
- [Work with EDRN page](https://edrn.nci.nih.gov/work-with-edrn/), in the "Member Finder" box
- [Sites page](https://edrn.nci.nih.gov/about-edrn/sites/), from the "Also try the Member Finder" link at the top

**Comment by hoodriverheather** [comment]
@nutjob4life I forgot about that issue, I'm getting old :( 
Thanks! H

**Comment by nutjob4life** [comment]
@hoodriverheather you and me both.

(Who are you again? Who am I? ☺️) 

Anyway, we've got a week. I think we could fit #213 in if you like.

**Comment by hoodriverheather** [comment]
@nutjob4life Is it a lot of work? I think it's up to you and your workload.

**Comment by nutjob4life** [comment]
@hoodriverheather done, see #213 

As for QC'ing _this_ issue, please try the member finder and ensure you can click on both the photo/silhouette and the name to get to the member.

**Comment by hoodriverheather** [comment]
@nutjob4life Thanks!
