### ISSUE TITLE
Data Sharing Policy under Bookshelf should link to current policy

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#303]
Link Data sharing policy should go to new data sharing policy on bookshelf - https://edrn-dev.jpl.nasa.gov/portal/renaissance/about-edrn/bookshelf/

Do we archive the old one?

**Comment by nutjob4life** [comment]
This is a content change, so I updated the link on the [production portal's bookshelf](https://edrn.nci.nih.gov/about-edrn/bookshelf/) and saved a copy of the old one.
