### ISSUE TITLE
Replace Member Finder views with Member Finder page on Home Page and About EDRN Page

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#304]
## 📕 Summary

With the [Member Finder Page live](https://github.com/EDRN/P5/issues/213), we need to replace links to old Member Finder View with the `MemberFinderPage`.

- [x] On [the home page](https://edrn.nci.nih.gov), there's a named view in the "Work with EDRN" box that should be replaced with a link to the `MemberFinderPage`
- [x] On [the Work with EDRN page](https://edrn.nci.nih.gov/work-with-edrn/), there's a link to a Member Finder landing page; this page should be deleted and the link should go to the `MemberFinderPage`.

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this, click on Member Finder and ensure you end up at the Member Finder from the following locations:

- [ ] From the [home page](https://edrn.nci.nih.gov/), in the cerulean box, the link text "Member Finder"
- [ ] From the [Work with EDRN page](https://edrn.nci.nih.gov/work-with-edrn/), in the navy box, the all-caps link text "MEMBER FINDER"

**Comment by hoodriverheather** [comment]
@nutjob4life looks good to me! All Member Finder links work. :)
