### ISSUE TITLE
On the Publications page, show only pubs from the DMCC, not BMDB

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#305]
See the title

**Comment by nutjob4life** [comment]
@hoodriverheather this is ready for QC. I recommend visiting the pubs page on the prod portal and the pubs page on the dev portal and scroll to the bottom on both. You'll see total № of publications. On dev portal, it should be lower since it's showing just DMCC-provided pubs.

**Comment by hoodriverheather** [comment]
@nutjob4life Thanks!!

**Comment by nutjob4life** [comment]
@hoodriverheather thank you! Closing this and freezing the code. 6.7 is done! 🎉
