### ISSUE TITLE
Please change link of Citing Data to point to page located in Bookshelf :)

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#306]
@nutjob4life I'm nervous to mess with this page. Would you please update the Citing Data link on this page

https://edrn.nci.nih.gov/data-and-resources/informatics/labcas-cancer-biomarker-data-commons/

to point to this page https://edrn.nci.nih.gov/about-edrn/bookshelf/citations/
that's under the bookshelf?

**Comment by nutjob4life** [comment]
@hoodriverheather I'm confused; when I visit [this page](https://edrn.nci.nih.gov/data-and-resources/informatics/labcas-cancer-biomarker-data-commons/) and hover my cursor over the "Citing data and Digital Object Identifiers (DOIs)" hyperlink, I see it's already pointing to https://edrn.nci.nih.gov/about-edrn/bookshelf/citations/

<img width="592" alt="Screenshot 2023-11-17 at 1 58 13 PM" src="https://github.com/EDRN/P5/assets/814813/8b0df185-2c31-4ea7-8d83-125be3e811d3">

Do you see something different?

**Comment by nutjob4life** [comment]
@hoodriverheather I'm going to go ahead and close this since from everything I can tell the link is already correct
