### ISSUE TITLE
Navigate from Publications to their matching Biomarkers

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#307]
## 🤔 Tell Us About the Feature

It'd be nice if, when viewing a publication, you could navigate to the biomarkers referencing that publication.

But this could be true of any "node" in the knowledge environment

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this:

1. Head to the [dev portal](https://edrn-dev.jpl.nasa.gov/portal/renaissance/) 
2. In the search box, type a publication like `Diagnostic markers for early detection of ovarian cancer` or `Construction and analysis of the NCI-EDRN breast cancer reference set for circulating markers of disease`
3. Visit the matching publication from the search results
4. Note the bottom of the page lists the biomarkers that make reference to the publication (at any level, biomarker, biomarker-organ, or biomarker-organ-study)

Note that for certain non-public biomarkers, such as `SAA@`, this does let you deduce that a certain publication is indeed referenced by the marker. This information is normally hidden on the biomarker's page. I don't know how big a deal that is.

**Comment by hoodriverheather** [comment]
@nutjob4life This is really cool!

**Comment by nutjob4life** [comment]
@hoodriverheather thank you!

**Comment by nutjob4life** [comment]
Adding "QC as per @hoodriverheather's comment; feel free to remove if disagree
