### ISSUE TITLE
Singular wording for multiple biomarkers

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#308]
## 🐛 Describe the Bug

On the [biomarker index page](https://edrn.nci.nih.gov/data-and-resources/biomarkers/) at the bottom, there's a yellow box that tells you that some biomarkers are currently being annotated or are under review. The boldface title of this box is "Non-Public Biomarker" (singular).

But it applies to all non-public biomarkers; so it should read "Non-Public Biomarkers" (plural).

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this, head over to the [dev portal's biomarker page](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/biomarkers/) while not logged in and scroll to the bottom. There, you should see "Non-Public Biomarkers" in the yellow box, _not_ "Non-Public Biomarker".

**Comment by hoodriverheather** [comment]
@nutjob4life Perfect!

**Comment by nutjob4life** [comment]
Adding "QC" as per @hoodriverheather's comment; feel free to remove if disagree
