### ISSUE TITLE
Improve social media in footer

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#311]
## 🤔 Tell Us About the Feature

Currently the EDRN portal's footer has links to Facebook and Twitter. These cannot be changed. We should have a way to update these as needed without software updates.

## 🎇 What Solution You'd Like

Make a social media control panel that doesn't hardcode Facebook and Twitter into the footer.

## 🗺 Context

First off, Twitter isn't Twitter anymore. And chances are, this so called "X" may just implode if its owner's behavior continues. Second, NCI has more social media than just Facebook. It also has Instagram, LinkedIn, and YouTube. Different divisions also have different social media.

If things suddenly change, we'd have to wait for a software change to update the social media. We need a better way.

**Comment by nutjob4life** [comment]
Hi @hoodriverheather this is ready! To QC this:

1. Visit the [dev portal](https://edrn-dev.jpl.nasa.gov/portal/renaissance/) and scroll down to the footer
2. Confirm you see icons for Facebook (and should go to the general NCI Facebook page), LinkedIn (and should go to the DCP LinkedIn page), and for X (should go to the DCP Twitter page)
3. [Log in as a super user](https://edrn-dev.jpl.nasa.gov/portal/renaissance/admin/)
4. From the Wagtail admin, click Snippets in the left-side menu, then Social media links
5. Click on X (for example) and un-check the "Enabled" box, then click Save
6. Click "Add social media link" and add a new one, such as name = `Instagram` (capital `I`), url = `https://www.instagram.com/nationalcancerinstitute/`, boostrap icon = `instagram` (lowercase `i`), enabled = ✓, then click Save
7. Because the footer is not expected to change often and is "heavily cached", we now need to clear the caches. Click the NIH logo in the left side menu, then click "Clear Caches". Or wait 7 days 😉
8. Return to [the home page](https://edrn-dev.jpl.nasa.gov/portal/renaissance/)
9. Confirm you see now Facebook, Instagram, and LinkedIn—and no X.

You don't have to put things back as it'll all be reset during the next nightly build.

**Comment by hoodriverheather** [comment]
@nutjob4life This totally works. However, i delete X instead of disabling (sorry, not sorry). Hope that doesn't mess up the nightly build.
Thanks!

**Comment by nutjob4life** [comment]
@hoodriverheather doesn't mess up a thing! After all, the entire site is blown up and we start from scratch each night. I look forwarding to including this in the next release. Thanks for the QC!
