### ISSUE TITLE
Add matching protocols to publications

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#313]
Just in the same way we do biomarkers (but based coordinatingInvestigatorSite (1), leadInvestigatorSite (1), and involvedInvestigatorSites (many))

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this:

- Visit any publication (such as [this one](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/publications/12036303-234-activation-of-the-esophagin-promoter-during-esophageal-epithelial-cell-differentiation) or [this one](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/publications/18024530-1587-seldi-tof-ms-whole-serum-proteomic-profiling-with-imac-surface-does-not-reliably-detect-prostate-cancer/) or [even this one](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/publications/36733187-3308-conditional-concordance-assisted-learning-under-matched-case-control-design-for-combining-biomarkers-for-population-screening/)) and look to see matching protocols.

Note: this results in _many many protocols_ on each publication, even those for which there is just one associated site. For example, site №5 (Feng Fred Hutch) is going to appear _all over_ because Feng Fred Hutch is on 316 different publications.

Take for example [the last publication](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/publications/36733187-3308-conditional-concordance-assisted-learning-under-matched-case-control-design-for-combining-biomarkers-for-population-screening/) I mentioned. In the data from the DMCC, this publication (PubMed 36733187) appears just once and is associated with just one site: №5, Feng Fred Hutch.

We then look at each protocol and find Feng Fred Hutch as a coordinating site, a lead site, or as an involved site, and gather them all up. That makes this single publication associated with 148 different protocols! Everything from breast to colon to lung to pancreas to prostate and other organs—and from MALDI Dilution Data to a Prospective Study to Establish a New Onset Hyperglycemia and Diabetes Cohort to the US-Turkey Cappadocia Mesothelioma Project.

Is this even remotely right?

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this:

1. Visit [this protocol](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/protocols/486-molecular-profiling-of-radical-prostatectomy-tissue-from-patients-with-no-sign-of-progression-identifies-independent-predictors-of-recurrence/) and note under "Publications" it says "No publications available at this time for this protocol".
2. Visit [this protocol](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/protocols/138-validation-of-protein-markers-for-lung-cancer-using-caret-sera-and-proteomics-techniques/) and note under "Publications" there is one publication. Click it to learn more about the publication. Note that the publication has a link back to the protocol.
3. Finally, visit [this protocol](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/protocols/237-high-throughput-evaluation-of-breast-cancer-markers/) and note that it has 7 publications.

**Comment by hoodriverheather** [comment]
@nutjob4life Awesome!
