### ISSUE TITLE
Data collection summary page

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#314]
You would see this page when clicking a data collection rather than being redirected into LabCAS.

It could show the publicly-available information about the data collection.

It would also have a large flashing button that would then lead you into LabCAS for that collection.

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this:

1. Visit the [dev portal](https://edrn-dev.jpl.nasa.gov/portal/renaissance/) and click "Data" on the home page or from the navigation menu
2. Pick a data collection, such as Autoantibody Biomarkers
3. Note that you no longer go to LabCAS, but instead get an interstitial page with the protocol, PI, organs, and biomarkers
4. Click the button to go to LabCAS. Note you are now in LabCAS

**Comment by hoodriverheather** [comment]
@nutjob4life Very cool!!
