### ISSUE TITLE
If there's no abstract available for a publication, we still show "Abstract" heading with blank space

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#319]
## 🐛 Describe the Bug

Check out [this publication](https://edrn.nci.nih.gov/data-and-resources/publications/11678032-1082-2-d-or-not-2-d-is-there-a-future-for-2-d-gels-in-proteomics-insights-from-the-york-proteomics-meeting/).

It's got an author, a PubMed ID, and tells even what journal it appears in. But under the heading "Abstract", there's just blank space.

We should do [what PubMed](https://pubmed.ncbi.nlm.nih.gov/11678032/) does for this publication and put some text there: _No abstract available_.

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this, check out [this publication](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/publications/11678032-1082-2-d-or-not-2-d-is-there-a-future-for-2-d-gels-in-proteomics-insights-from-the-york-proteomics-meeting/) which has no abstract. You should see "No abstract available" under the "Abstract" heading.

**Comment by hoodriverheather** [comment]
@nutjob4life 👍
