### ISSUE TITLE
Documents → Agendas

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#321]
In a call with Jackie, Jackie expressed a desire to change the "Documents" heading to "Agendas" in committees pages.

But not in all committees. For example, in the Data Sharing group, it should remain "Documents".

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this:

1. [Log into the dev portal](https://edrn-dev.jpl.nasa.gov/portal/renaissance/_util/login/?next=/portal/renaissance/) as a super user
2. Go to [the committees and collaborative groups. page](https://edrn-dev.jpl.nasa.gov/portal/renaissance/about-edrn/groups/) and pick any committee or group
3. Note that the heading is "Documents"
4. Click the NIH badge in the corner and click "Edit this page"
5. Under "Documents heading", change "Documents" to "Agendas", then press "Publish"
6. Press the "View Live" button and ensure complete Documents → Agendas transition

No need to change it back; the dev portal rebuilds itself nightly.

**Comment by hoodriverheather** [comment]
@nutjob4life That is cool!! I think it's great to have this feature, but now that the DMCC is using the Events it might be OK to keep that labeled as Documents :)

**Comment by nutjob4life** [comment]
Thanks @hoodriverheather! 🎉
