### ISSUE TITLE
Create private image reader training page(s)

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#326]
@nutjob4life I don't know if  Ashish or Dan mentioned on the Tuesday staff call that we would like to setup a secure page on the EDRN Portal that would provide a place to post training docs and examples for the Image Readers. They all belong to an LDAP group that was setup in the MCL LDAP (I think we can use the Lung Image Reader Set 1, but i need to confirm).

This page should have a basic description of The Image Reader Study and then links to quite a few pdf files. 

Something like this:
![image](https://github.com/EDRN/P5/assets/58526347/8b466077-ae6f-44fe-ad0e-692adef67f94)

I can add text and docs if you would please setup a page. It shouldn't be linked on any of the Portal menus, we will just send them the link. Thanks!

**Comment by nutjob4life** [comment]
Hi @hoodriverheather, the EDRN portal "belongs" to EDRN. That is, it only knows about the EDRN branch in the directory. The MCL branch doesn't exist as far as the portal is concerned.

If you like, we can copy those two groups from MCL to EDRN. But, is this okay? (I thought the Consortium for Molecular and Cellular Characterization of Screen-Detected Lesions was dead!)

**Comment by hoodriverheather** [comment]
@nutjob4life closing, as we are doing this in MCL LabCAS :)
