### ISSUE TITLE
Support for AHEAD sites

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#327]
## 🤔 Tell Us About the Feature

[Jackie Dahlgren](mailto:jdahlgre@fredhutch.org) writes:

> We added a new type of Site that is called AHEAD.  Will you please do a refresh and see if the data pulls over to this page on the Portal?

## 🎇 What Solution You'd Like

We need to know where these AHEAD sites should sit on the sites page and what AHEAD stands for.

**Comment by nutjob4life** [comment]
Clarification from Jackie Dahlgren:

- AHEAD = Advancement of Head and Neck Cancer Early Detection Research
- And they should be at the very end of the sites list

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this please visit [the Sites page](https://edrn-dev.jpl.nasa.gov/portal/renaissance/about-edrn/sites/) and check that there's an AHEAD item in the list of site kinds near the top (under the map) and if you click on the AHEAD it takes you to an AHEAD section with 14 different sites.

**Comment by hoodriverheather** [comment]
@nutjob4life Sorry to get to this so late! I only work a few hours on Fridays. This looks great, can you sneak it in the release?

**Comment by nutjob4life** [comment]
I won't tell if you won't tell @hoodriverheather 🤫
