### ISSUE TITLE
Data Dispatcher

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#33]
We need a data dispatcher.

## Explanation

The various objects of the EDRN Knowledge Environment (EKE) all have unique RDF identifiers (URIs), such as `http://edrn.jpl.nasa.gov/bmdb/biomarkers/view/747` being the MTO1 biomarker or `urn:edrn:data:null` being the null EKE object. These are URIs that aren't necessarily URLs, though, which is fine in RDF.

For SEO reasons, the portal uses readable URLs that don't match the URIs. For example, the protocol with RDF URI `http://edrn.nci.nih.gov/data/protocols/421` is could live at https://edrn.nci.nih.gov/protocols/421-a-biomarker-bakeoff-in-early-stage-pancreatic

When other applications like LabCAS want to link to that protocol, though, they know the RDF URI, but can't reliably generate `421-a-biomarker-bakeoff-in-early-stage-pancreatic`.

## Implementation

It'd be great if the portal had an endpoint like

```
https://edrn.nci.nih.gov/dispatch?id=URI
```

where `URI` could be any URI. For example, you could plug in

```
https://edrn.nci.nih.gov/dispatch?id=http://edrn.nci.nih.gov/data/protocols/421
```

and the software would give an automatic redirect to `https://edrn.nci.nih.gov/protocols/421-a-biomarker-bakeoff-in-early-stage-pancreatic`.

This way LabCAS wouldn't need to duplicate how Plone generates URLs and ease @yuliujpl's life.

**Comment by nutjob4life** [comment]
Calling it `dataDispatch` and the parameter is `subjectURI`.

**Comment by nutjob4life** [comment]
@hoodriverheather to test this, try:

1. Ensure the JPL VPN is running
2. Open a Terminal
3. Enter the following command:

```bash
curl -sv 'https://edrn-dev.jpl.nasa.gov/portal/5/dev/@@dataDispatch?subjectURI=http://edrn.nci.nih.gov/data/protocols/421'
```

Make sure to paste in the entire command line, starting with `curl` and ending with `421'` complete with the final apostrophe.

In the output, look for these specific lines:
```
< HTTP/1.1 302 Moved Temporarily
…
< Location: https://edrn-dev.jpl.nasa.gov/portal/5/dev/protocols/421-a-biomarker-bakeoff-in-early-stage-pancreatic
```

If they're not present please re-open the issue 👻

**Comment by hoodriverheather** [comment]
Returned above output.
