### ISSUE TITLE
Show start, estimated finish, and finish dates on protocols

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#338]
Title says it all

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this, head to the [dev portal](https://edrn-dev.jpl.nasa.gov/portal/renaissance/) and type "118" or "Biomarker Reference Sets for Cancers in Women" in the search box and click through to that protocol.

Then check out the right-hand side: you should see start date, estimated finish date, and finish date.

**Comment by hoodriverheather** [comment]
👍
