### ISSUE TITLE
More focused login form

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#339]
## 🤔 Tell Us About the Feature

We have a [login form](https://edrn.nci.nih.gov/_util/login/?next=/) on the portal that helps people end up where they really want to be—whether that's the portal itself, LabCAS, or the "secure" site.

However, when we have a protected resource such as a biomarker and we encourage people to log in to gain additional information, they go back to that main login form—which presents the three options.

What they really want is to just log into the portal.

## 🎇 What Solution You'd Like

Have a focused portal login form that doesn't present the other two options (LabCAS, DMCC) when the context is clear.

## 🗺️ Context

Inspired by #323

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this visit the [dev portal](https://edrn-dev.jpl.nasa.gov/portal/renaissance/) while not logged in and search for "4DELF" and click the organs tab. In the yellow box, click the "logging in" link; you should end up at the focused login page that does _not_ present the LabCAS or "secure" site options.

Then, navigate to the [biomarkers page](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/biomarkers/) while not logged in and scroll to the bottom. In the yellow box, click the "logging in" link; you should end up again at the focused login form.

Finally, click the "Log in" link in the upper right; confirm you end up at the multiple-destination login form (porta, LabCAS, "secure" site).

**Comment by hoodriverheather** [comment]
@nutjob4life this is awesome! Could you also implement this for other places on the portal that ask users to login to view a page? For example, the Collaborative Groups? https://edrn-dev.jpl.nasa.gov/portal/renaissance/_util/login/?next=/portal/renaissance/about-edrn/groups/breast-and-gynecologic-cancers-research-group/

**Comment by nutjob4life** [comment]
@hoodriverheather probably, but I'd like to hold off.

Any work put into making it happen for this issue, #339, will just have to be ripped out when we resolve #323—which is also going to happen in this milestone.

Is that okay?

**Comment by hoodriverheather** [comment]
@nutjob4life Holding off until next milestone is a great idea. Thanks!
