### ISSUE TITLE
Add PI to the "wall of [REDACTED]" at /data-sharing

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#341]
Like the title reads, we want both the site and the PI to show when viewing the sites who have and haven't signed their data sharing agreements

**Comment by nutjob4life** [comment]
@hoodriverheather to QC thiis, visit [the data sharing page on the dev portal](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-sharing) and ensure the display includes the above

**Comment by hoodriverheather** [comment]
Perfect!

**Comment by nutjob4life** [comment]
Thanks much 🎉
