### ISSUE TITLE
Display of Executive Committee and Network Consulting Team

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#342]
@hoodriverheather found a few discrepancies when comparing to the DMCC Secure Site:
- Executive Committee lists members on Portal, but not on Secure Site
- Network Consulting Committee lists chair, but on Secure Site also lists members - Are we allowed to show this at all (i'm logged in as a Super User)

The SOAP API gives a chair, co-chair, and 11 members for the Executive Committee. The DMCC can explain why SOAP API gives people while they don't show any on their own "secure" site.

The SOAP API for commmittees shows a chair and 5 members for the Network Consulting Team:

| Person ID | Name                     | Site ID |
|----------:|:-------------------------|--------:|
| 4326      | Polyak, Kornelia (Nelly) | 928     |
| 4327      | Johnson, Bruce           | 929     |
| 4328      | Olopade, Funmi           | 930     |
| 4329      | Lidgard, Graham          | 931     |
| 4330      | Philip, Reena            | 932     |

However, the SOAP API for sites gives no information about sites 928, 929, 930, 931, or 932. In the portal, we have to associate people with sites. Since none of these sites exist, the portal cannot create the people, so the Network Consulting Team shows no members.

(This started [as a comment to #324](https://github.com/EDRN/P5/issues/324#issuecomment-1940130565).)

**Comment by hoodriverheather** [comment]
@nutjob4life Still waiting to hear back from DMCC. "I think I see the problem – These sites are set to Not Active.  I have to find out from Royce if the Network Consulting Teams were supposed to be inactivated or not.  I’ll get back to you.  Jackie
 "  
I'm following up.
