### ISSUE TITLE
Image left/right setting should float images left/right

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#343]
On the P5 portal, after inserting an image, choosing "left" or "right" should cause the image to float left or right with the text wrapping around.

This doesn't happen. Instead, the image appears as a separate block element.

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this:

1. [Log in](https://edrn-dev.jpl.nasa.gov/portal/renaissance/_util/login/?next=/portal/renaissance/_util/login/) as an editor on the dev portal
2. Visit the [five phase design page](https://edrn-dev.jpl.nasa.gov/portal/renaissance/about-edrn/five-phase-approach-and-prospective-specimen-collection-retrospective-blinded-evaluation-study-design/)
3. Click the NIH badge and choose to edit the page
4. Click the pyramid image and click Edit
5. Change "Format" from "Full width" to "Left-aligned", then click "Insert image", then "Publish"
6. Note that the image floats left and the text wraps to the right, as follows:

<img width="1213" alt="Screenshot 2024-02-15 at 3 40 42 PM" src="https://github.com/EDRN/P5/assets/814813/0630e7a9-174c-4f44-be24-fc0d99145bce">

_Note:_ If you don't see this, you will need to clear your browser cache and/or use a Force Reload on the page. This patch relies on a stylesheet change and stylesheets are heavily cached (24 hours).

Now repeat this and change the "Left-aligned" to "Right-aligned". Now you should get this:

<img width="1201" alt="Screenshot 2024-02-15 at 3 42 18 PM" src="https://github.com/EDRN/P5/assets/814813/2ee6e658-040f-4e7b-98ac-299ca55ed7e0">

Finally, edit the page a third time and set the image back to "Full width". It should return to how it was.

**Comment by hoodriverheather** [comment]
@nutjob4life Looks good. I had to test it in incognito :)

**Comment by nutjob4life** [comment]
Thanks @hoodriverheather! And with that, [milestone 6.10](https://github.com/EDRN/P5/milestone/33) is closed on time! Woooooot! 🎉
