### ISSUE TITLE
Early Career Working Group doesn't appear on committees page

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#345]
## 🐛 Describe the Bug

The "Early Career Working Group" was added to the RDF. However after a nightly ingest, this group doesn't appear on [the committees page on the portal](https://edrn.nci.nih.gov/about-edrn/groups/).

In fact, _nothing_ can be added under the committees page.

## 🔎 Expected Behavior

We should be able to add new groups and then have their details populated via RDF.

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this, try the following:

1. Visit [the dev portal and log in as an editor or super user](https://edrn-dev.jpl.nasa.gov/portal/renaissance/_util/login/?next=/portal/renaissance/)
2. Visit the [committees page](https://edrn-dev.jpl.nasa.gov/portal/renaissance/about-edrn/groups/) and click the NIH badge in the corner and click "Add child page"
3. For the page title, enter `Early Career Working Group`
4. For the ID number, enter 54. You can leave everything else blank; click Publish
5. Go to the [Wagtail admin](https://edrn-dev.jpl.nasa.gov/portal/renaissance/admin/) and click "Full Ingest"
6. Wait 15 minutes
7. Go to the new [Early Career Working Group page](https://edrn-dev.jpl.nasa.gov/portal/renaissance/about-edrn/groups/early-career-working-group/) and note that the program officer, project scientists, and members are now filled in.

**Comment by nutjob4life** [comment]
Not QC'd for 6.11 so postponing to 6.12

**Comment by nutjob4life** [comment]
@hoodriverheather oops! This accidentally got included in 6.11 and is now live in production. Could you quickly slap a QC label on this?

Ignore [these instructions](https://github.com/EDRN/P5/issues/345#issuecomment-1966970131) as they only applied for development.

The new QC procedure would be:

1. [Visit this group](https://edrn.nci.nih.gov/about-edrn/groups/early-career-working-group/) and make sure it has a program officer, project scientists, and members
2. Then [visit this group](https://edrn.nci.nih.gov/about-edrn/groups/biomarker-reference-laboratories/) and make sure it has project scientists, a chair, and members

**Comment by hoodriverheather** [comment]
@nutjob4life Looks great! :)

**Comment by nutjob4life** [comment]
@hoodriverheather thank you! Could you let Jackie D know that the two new groups are now live? As a reminder, they are:

- The Early Career Working Group at https://edrn.nci.nih.gov/about-edrn/groups/early-career-working-group/
- The Biomarker Reference Laboratories at https://edrn.nci.nih.gov/about-edrn/groups/biomarker-reference-laboratories/
