### ISSUE TITLE
On the Biomarkers page, add a feature to submit new biomarkers

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#346]
We've been tossing around the idea of adding a feature to the portal for members to submit new biomarkers for consideration for inclusion in our repertoire of 1600+ biomarkers. This could be anything from a simple email link to a form to fill out. Specifications and requirements to follow for possible inclusion in P5 portal version 6.11

**Comment by nutjob4life** [comment]
Update from @hoodriverheather via email:

> It could read, “Missing your biomarkers? Inform us about your EDRN-funded project’s biomarkers.”

**Comment by nutjob4life** [comment]
@dcrichto1 @kristenanton @mryan4 @hoodriverheather if we want to include this feature in 6.11 (code freeze date 2024-03-15) I will need specifications on how you want this to look by COB today (2024-03-08) in order to allow sufficient time for implementation, feedback, and testing.

Of course we can postpone this to 6.12 (code freeze 2024-04-20). Just let me know by commenting here! 😁

**Comment by hoodriverheather** [comment]
@nutjob4life 
Setup a form in Wagtail that’s similar to the [High-level Data Submission Form](https://urldefense.us/v3/__https://edrn.nci.nih.gov/data-and-resources/cde/labcas-metadata-and-common-data-elements/metadata-collection-form/__;!!PvBDto6Hs4WbVuu7!In1L7G2nD58-KIcXK3S2M-zHLsYAL-Twoa_TAchGv6cv9oa06qjU32_cr8fg0FKHsV4ghrYctyPjVM004QgoQe3p9e0pZsU$) for LabCAS. I will work on some added descriptions/directions for some of the fields to come a bit later.
 
The form will include:
Submitter Name (required)
Submitter Email (required)
Biomarker(s): Include a way for them to upload a document or copy and paste a large list (required)
Lead PI (same as PI/Institution list in Data Submission form) (required)
Protocol (same as Data Submission form pick list)
Organ pick list
Type – check all that apply. (Molecular, Histologic, Radiographic, Physiological)
Molecular SubType – pick list. (Chemical, Protein, DNA (Genetics), Karyotypic
PubMed ID or Name of Publication

**Comment by nutjob4life** [comment]
@hoodriverheather you can see a [first cut at this form](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/biomarkers/biomarker-submission-form/). 

Email isn't working on tumor.jpl.nasa.gov for some reason, but you can at least get a feel for how the form looks and works. If email were working, submitting the form would send an email to you and me with the form data (and optional attachment).

**Comment by hoodriverheather** [comment]
@nutjob4life This is looking great. From my notes when meeting with Kristen and Maureen. Only submitter name and email should be required and the captcha. :)

Also, can you update the instructions under protocol? See attached. We can also ask Maureen and Kristen tomorrow on the staff call.
thanks!
<img width="975" alt="Screenshot 2024-03-11 at 10 36 51 AM" src="https://github.com/EDRN/P5/assets/58526347/01be378a-0786-4984-9a94-bef63117e28f">

**Comment by mryan4** [comment]
Yes, looks great! Thanks Sean. 
And you are right, Heather. We don’t want to require the protocol ID, because if they don’t have it they just won’t submit.

Maybe require investigator and organ, though? Let’s discuss tomorrow. 


Maureen Ryan (Contractor)
Division of Gastroenterology & Hepatology 
Department of Medicine
UNC at Chapel Hill





On Mar 11, 2024, at 1:43 PM, hoodriverheather ***@***.***> wrote:


@nutjob4life <https://github.com/nutjob4life> This is looking great. From my notes when meeting with Kristen and Maureen. Only submitter name and email should be required and the captcha. :)

Also, can you update the instructions under protocol? See attached. We can also ask Maureen and Kristen tomorrow on the staff call.
thanks!
Screenshot.2024-03-11.at.10.36.51.AM.png (view on web) <https://github.com/EDRN/P5/assets/58526347/01be378a-0786-4984-9a94-bef63117e28f>

**Comment by nutjob4life** [comment]
@hoodriverheather @mryan4 I've made updates to the form. Should be ready in about 15 minutes.

**Comment by hoodriverheather** [comment]
@nutjob4life Reviewing this with Maureen and Kristen. Can you add the following field - > Associated Publication (e.g. pubmedID or publication title).

**Comment by nutjob4life** [comment]
@hoodriverheather added; expect new dev portal in ~12 minutes

**Comment by hoodriverheather** [comment]
Perfect! Thanks!
