### ISSUE TITLE
For the metadata collection form, add a "Biomarkers researched" field

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#347]
## 🤔 Tell Us About the Feature

@hoodriverheather wrote in email:

> Additionally, consider updating the [metadata-collection-form](https://edrn.nci.nih.gov/data-and-resources/cde/labcas-metadata-and-common-data-elements/metadata-collection-form/) to follow the Protocol section with a new question: “Biomarkers researched,” incorporating a free-text field for responses

## 🎇 What Solution You'd Like

Add a paragraph text entry box labeled "Biomarkers researched" under the Protocol section.

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this, first alter the form's email recipients to avoid bothering anyone:

1. Visit the [dev portal and log in](https://edrn-dev.jpl.nasa.gov/portal/renaissance/_util/login/?next=/portal/renaissance/) as an administrator
2. Next, visit the [metadata collection form](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/cde/labcas-metadata-and-common-data-elements/metadata-collection-form/) and click the NIH badge in the corner and choose "Edit this page"
3. Change the "To address" to just your email address.
4. Click "Publish".

Now you can QC the form's new feature:

1. Visit the [metadata collection form](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/cde/labcas-metadata-and-common-data-elements/metadata-collection-form/) and fill out the form.
2. Fill out the form, but take note of the new "Biomarkers Researched" field, and enter some distinctive text here
3. Submit the form
4. Wait a few minutes, then check your email
5. Ensure the distinctive text you entered appears in the email

Note: There's no need to reset the "To address" back after testing; this is a dev portal after all and it's rebuilt in its entirety nightly.

**Comment by hoodriverheather** [comment]
@nutjob4life The form looks great. I may have some additional updates to it based on trainings and generating the biomarker form. 
I got this error when i submitted.
<img width="1290" alt="Screenshot 2024-03-12 at 4 20 10 PM" src="https://github.com/EDRN/P5/assets/58526347/0bc3d78d-146b-47e8-b1bc-aa2684f1ace7">


I'm also wondering if we should make protocol not required. I have some draft screenshots.

**Comment by nutjob4life** [comment]
The form generates an email and email sending on tumor.jpl.nasa.gov is currently broken. I've got a follow up with the system administrators. But trust me 😉 it will work at NCI.
