### ISSUE TITLE
Add "outcome" and "secure outcome" to protocols

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#348]
## 🤔 Tell Us About the Feature

Based on discussion on 2024-04-14 (happy Pi day), the biomarker systems planning meeting would like to have the "outcome" and the "secure outcome" displayed on protocols.

## 🎇 What Solution You'd Like

How about "outcome" for everyone, and "secure outcome" for people logged in?

## 〽️ Alternative Ideas

We don't have group permissions for protocols, but if we did we could filter who saw "secure outcome" based on logged-in group membership. So for now, it's "secure outcome" for people logged in.

## 🗺 Context

Cancer biomarker systems planning, 2024-04-14

**Comment by nutjob4life** [comment]
@hoodriverheather does the above ↑ sound fair? I think I can get this implemented in time for 6.11 code freeze tomorrow, but I don't want to eat into your time so close to the freeze date 😳

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this, visit the [dev portal](https://edrn-dev.jpl.nasa.gov/portal/renaissance) and bring up a protocol like №137 (you can just type 137 in the main search box).

Note that there is an Outcome.

Now log in and revisit that protocol. Now there's an Outcome and a Secure Outcome.

(I checked the data from the DMCC's SOAP as well as visiting the "secure" site and it seems in the cases where there's a Secure Outcome it's identical to the Outcome—every single time. I don't know how useful this is to display. Maybe since it's the _public_ portal, just Outcome and drop this Secure Outcome nonsense?)

**Comment by hoodriverheather** [comment]
@nutjob4life i need to test, but i really think we should wait on showing the secure outcome. Just show the public outcome.

**Comment by nutjob4life** [comment]
@hoodriverheather okay, hiding secure outcome. Expect a new dev portal in ~12 minutes

**Comment by hoodriverheather** [comment]
Awesome! Thanks!

**Comment by nutjob4life** [comment]
QC'd in time for 6.11 code freeze so moving from 6.12 👍
