### ISSUE TITLE
Ingest new Publications

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#35]
Ingest publications found based on grant numbers provided by Christos.
 - Add only new publications, ignore existing publications
https://edrn.nci.nih.gov/publications
[EDRNgrant_to_pubmed-excel.xlsx](https://github.com/EDRN/P5/files/4789047/EDRNgrant_to_pubmed-excel.xlsx)

**Comment by nutjob4life** [comment]
@hoodriverheather how will updates to this list of grant numbers be provided?

-   Do we want a list box on the portal where we can type in the list of grant numbers?
    -   Given Dan's adverse reactions to "curating on the portal", I'd guess he'd say 👎
    -   But it'd be pretty simple to provide for the next milestone release 👍
        -   So if speed it the issue, I'd lean toward this
-   Should KSDB provide a curation page for grant numbers instead?

**Comment by nutjob4life** [comment]
Removed the "content" label; this will require software changes, perhaps to [P5](https://github.com/EDRN/P5), perhaps to [CancerDataExpo](https://github.com/EDRN/CancerDataExpo), perhaps to [KSDB](https://github.com/EDRN/KSDB). Added "enhancement" tag since it's a new feature.

**Comment by nutjob4life** [comment]
Informatics Center status meeting 2020-06-23:

-   Dan says to curate the grant number list in the portal itself
    -   Portal will then correlate that with publications with PubMed queries
-   Removing @hoodriverheather from assignees since the question in the comment above is now answered 😉

Correlating publications with collaborative groups or PIs is usually a "one-off report" and we should "write no code" for that at this time.

**Comment by nutjob4life** [comment]
@hoodriverheather to confirm this, please try the following:

1. Visit https://edrn-dev.jpl.nasa.gov/portal/5/dev/
2. Log in with any account with Manager privileges
3. Click Publications
4. Click Edit in the Plone control bar
5. Confirm there is a "Grant Numbers" box on the page that's populated with grant numbers `CA086368`, `CA086400`, …, `CA214201`.
6. Click Cancel
7. In the "Search" box beneath "Items published by EDRN." enter: `Detecting protein variants by mass spectrometry: a comprehensive study in cancer cell-lines` and press "Search"
8. Confirm there is one matching publication beneath the bar graph.

If this doesn't mesh with reality, please re-open the issue 💔
