### ISSUE TITLE
Googlebot attempts to crawl /authentication-test

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#359]
## 📕 Summary

The Google search engine crawler complains that it cannot index the page https://edrn.nci.nih.gov/authentication-test because it keeps getting an error, "401 Forbidden".

Which it should be getting, as that URL is just used for testing to see if the portal can authenticate users. It should not be index.

This URL should be added to the disallowed URL list in the robots.txt configuration.

**Comment by nutjob4life** [comment]
Fixed TTW (through the web).

@hoodriverheather to QC this, visit https://edrn.nci.nih.gov/robots.txt and ensure `Disallow: /authentication-test` appears as one of the URLs that search engines are disallowed from entering.

**Comment by hoodriverheather** [comment]
@nutjob4life confirmed.
