### ISSUE TITLE
Add additional fields to the Data Submission Form

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#366]
## 🤔 Tell Us About the Feature

Please add the following additional fields and descriptions to the Data Submission Form https://edrn.nci.nih.gov/data-and-resources/cde/labcas-metadata-and-common-data-elements/metadata-collection-form/

- Method Details. Description to show below the field on the form - A comprehensive description of the methodologies and procedures used in the collection and processing of the dataset. This includes information on the experimental design, data collection techniques, equipment used, protocols followed, and any specific conditions or settings applied during the data acquisition process. Additionally, it captures details about any tools, software, or algorithms utilized in data processing and analysis, ensuring transparency and reproducibility of the research.

- Instrument. Description - The specific device or apparatus used to generate the data. This can include mass spectrometers, sequencers, imaging devices (e.g., MRI, CT, Mammogram), and other specialized tools employed in the data collection process.

These should both be required.
Thanks!
Heather

**Comment by nutjob4life** [comment]
Added to September 20th milestone (6.14)

**Comment by nutjob4life** [comment]
@hoodriverheather couple quick questions:

- **Method Details**. This should be a large text box, right? Where should it go on the form? After "Data Custodian Email"? 
- **Instrument**. This should be a single line field, right? Where should it go? Maybe above "Data Category"?

**Comment by hoodriverheather** [comment]
@nutjob4life Good questions.

You're correct on size of text boxes.
They could both go above "Data Category"

Two additional items i noticed:

-  please make Results and Conclusion Summary required
- please move Private Data and Shared Access above Comments or Questions.
Thanks!

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this:

1. [Visit the form on the dev site](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/cde/labcas-metadata-and-common-data-elements/metadata-collection-form/)
2. Fill out the form, especially noting the new **Method Details** field, the **Instrument** field, the now-required **Results and Conclusion Summary** field, and the re-located **Shared Access** field and **Private Data** checkbox
3. Submit the form and watch your email for the results

**Comment by nutjob4life** [comment]
Live as of 2024-09-03
