### ISSUE TITLE
Multiple co-chairs per committee

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#368]
## 🤔 Tell Us About the Feature

Royce said in an email that she expected two co-chairs for the [Statistical Working Group](https://edrn.nci.nih.gov/about-edrn/groups/statistical-working-group/) and the [Lung Collaborative Group](https://edrn.nci.nih.gov/about-edrn/groups/lung-and-upper-aerodigestive-cancers-research-group/), but she's only seeing one each.

That's because the portal's data model is to have just one co-chair.

## 🎇 What Solution You'd Like

Make it so that a committee/working group/collaborative group/etc. can have multiple co-chairs.

## 〽️ Alternative Ideas

Can't think of any alternatives.

## 🗺 Context

See Royce's email with Message ID `< MN2PR11MB4045E2580F3D8ADF1A8B9E72A79E2@MN2PR11MB4045.namprd11.prod.outlook.com>`

**Comment by nutjob4life** [comment]
This is done, but as of 2024-09-11, JPL border firewall is blocking my access so I can't actually deploy this to the dev site.

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this:

1. Visit the [dev site lung collab group](https://edrn-dev.jpl.nasa.gov/portal/renaissance/about-edrn/groups/lung-and-upper-aerodigestive-cancers-research-group/) and ensure you see two co-chairs
2. Visit the [dev site stat working group](https://edrn-dev.jpl.nasa.gov/portal/renaissance/about-edrn/groups/statistical-working-group/) and ensure you see two co-chairs

**Comment by hoodriverheather** [comment]
@nutjob4life Perfect!

**Comment by nutjob4life** [comment]
@hoodriverheather thanks!
