### ISSUE TITLE
Add Metabolomics to the Data Submission Form

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#369]
## 🤔 Tell Us About the Feature

@nutjob4life on the Data Submission form please add the following to the Discipline field:
- Metabolomics
- Other

Remove - Undefined

Add a new field to capture Other Discipline.

**Comment by nutjob4life** [comment]
@hoodriverheather done the following:

- Added Metabolomics to the [collection](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/cde/labcas-metadata-and-common-data-elements/metadata-collection-form/) and [dataset](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/cde/labcas-metadata-and-common-data-elements/dataset-metadata-form/) forms
- Added Other Discpline to the [collection](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/cde/labcas-metadata-and-common-data-elements/metadata-collection-form/) and [dataset](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/cde/labcas-metadata-and-common-data-elements/dataset-metadata-form/) forms
- Replaced misspelled "Imagess" → Images as a free bonus

To QC, visit each form and try them out.

**Comment by hoodriverheather** [comment]
@nutjob4life looks great.
