### ISSUE TITLE
Certain text causes collection data submission form to fail

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#370]
## 🐛 Describe the Bug

Entering this text into the "Results and Conclusion Summary" of the data submission form causes it to crash:

> Emerging evidence implicates microbiome involvement in the development of pancreatic cancer (PaCa). We investigated whether increases in circulating microbial-related metabolites are associated with PaCa risk by applying metabolomics profiling to 172 sera collected within five years prior to PaCa diagnosis and 863 matched non-case sera from participants in the Prostate, Lung, Colorectal and Ovarian (PLCO) Cohort. Using a subset of specimens from seven PLCO centers, a three-marker microbial-related metabolite panel was developed to assess 5-year risk of PaCa. The panel was validated using samples from three different PLCO centers as well as a separate cohort of newly-diagnosed PaCa cases and controls. The addition of five non-microbial metabolites further improved 5-year risk prediction of PaCa. The combined metabolite panel was complementary with CA19-9 and individuals with a combined metabolite panel plus CA19-9 score in the top 2.5th percentile had absolute 5-year risk estimates of >13%. The risk prediction model based on circulating microbial- and non-microbial metabolites provides a potential tool to identify individuals at high-risk of pancreatic cancer and who would benefit from surveillance and/or from potential cancer interception strategies. 

## 📜 How To Reproduce

Visit the [data submission form](https://edrn.nci.nih.gov/data-and-resources/cde/labcas-metadata-and-common-data-elements/metadata-collection-form/) and enter the above text.

## 🔎 Expected Behavior

It should go through.

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this, visit the [dev data submission form](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/cde/labcas-metadata-and-common-data-elements/metadata-collection-form/) and fill out the form, using the text in the description above in one or more of the larger fields.

Submit the form. It should go through without a server error.

**Comment by hoodriverheather** [comment]
@nutjob4life Thanks for figuring this out so quickly.

**Comment by nutjob4life** [comment]
@hoodriverheather thanks for confirming it! 👍
