### ISSUE TITLE
Update the Collection Metadata form to use LeadPI, Organ and Institution when creating the .cfg

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#372]
can you update the Collection Metadata form to use LeadPI, Organ and Institution when creating the .cfg file? Also, update the .cfg to match values in the pick lists and no hyphens? See the EDRN data model collection tab - https://docs.google.com/spreadsheets/d/11AmL5bhHCjBxhx9k9MXortYDNYuuW1Unn7c8sx-z_dE/edit?pli=1&gid=0#gid=0

Originally requested by @hoodriverheather in [this comment](https://github.com/EDRN/EDRN-metadata/issues/118#issuecomment-2369012892)

Also, @hoodriverheather mentioned during staff call (2024-10-08), the DataDisclaimer should be included automatically

**Comment by hoodriverheather** [comment]
@nutjob4life Please also have the output match the metadata name values (column A) of this sheet. I've updated these to match what the UI is expecting 
    https://docs.google.com/spreadsheets/d/11AmL5bhHCjBxhx9k9MXortYDNYuuW1Unn7c8sx-z_dE/edit?pli=1&gid=0#gid=0
Thank you!!

**Comment by nutjob4life** [comment]
@hoodriverheather I'm finally working on this. I wanted to confirm something in [the above referenced google sheet](https://docs.google.com/spreadsheets/d/11AmL5bhHCjBxhx9k9MXortYDNYuuW1Unn7c8sx-z_dE/edit?pli=1&gid=0#gid=0); in cell B16, the last permissible value is `Antibody Microarra` for `DataCategory`? Thanks in advance!

**Comment by hoodriverheather** [comment]
@nutjob4life Thanks for catching this. I added the "y" at the end. :)

**Comment by nutjob4life** [comment]
@hoodriverheather  I've committed code to achieve the changes outlined above.

To QC this:

1.  [Visit the form on the dev site](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/cde/labcas-metadata-and-common-data-elements/metadata-collection-form/)
2.  Confirm that all permissible values in the form match those in column B; in particular, these were updated:
    -   "Cancers Research Group" dropped from collaborative group names
    -   For `DataCategory`, confirm the `y` still appears on `Antibody Microarray`
3. Fill out and submit the form. Try to fill out every field.

In the email that is generated, note the following:

1.  Instead of codes with hyphens, check that full names of metadata values are in the generated email for the following fields:
    -   `Discipline`
    -   `DataCategory`
    -   `Species`
2.  Check that "Name" has been removed from metadata keys as follows (matching column A):
    -   `InstitutionName` → `Institution`
    -   `LeadPIName` → `LeadPI`
    -   `OrganName` → `Organ`
    -   But: `ProtocolName`, `ProtcolAbbreviatedName`, and `CollectionName` remain untouched
3.  Confrim that LabCAS's weird capitalization is enforced as follows (matching column A):
    -   `InstitutionID` → `InstitutionId`
    -   `LeadPIID` → `LeadPIId`
    -   `OrganID` → `OrganId`
    -   `ProtocolID` → `ProtocolId`
    -   But: `PubMedID` remains as is
4.  Check that the following two fields have moved from being appended to the end of the email, to being "fields" in the metadata (column A):
    -   `Instrument`
    -   `MethodDetails`
    -   (These remain as appended to the end of the email, if filled in: comments, biomarkers researched, additional site, type of data being uploaded, other discipline)
5.  See if the field `DataDisclaimer` is always filled in; its text can be changed on Wagtail's "Snippets" control panel

**Comment by hoodriverheather** [comment]
@nutjob4life This looks great. I think we may have more updates once we have the FAIR Guidance in better shape. If it's possible to make this small change that would be great, if not it can happen later. Thanks!
In the text under Biomarkers Researched. Can you update to read: Enter the name(s) of the cancer biomarker(s) associated with the data being deposited.

**Comment by nutjob4life** [comment]
@hoodriverheather text changed from

    Describe the cancer biomarkers being researched by this data.

to

    Enter the name(s) of the cancer biomarker(s) associated with the data being deposited.

This is now live on [the form on the dev portal](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/cde/labcas-metadata-and-common-data-elements/metadata-collection-form/)

 If this looks okay, please go ahead and close this issue. If not, describe what else needs changing and re-assign back to me

**Comment by hoodriverheather** [comment]
@nutjob4life looks great. thanks!

**Comment by nutjob4life** [comment]
@hoodriverheather this is now [live in production](https://edrn.nci.nih.gov/data-and-resources/cde/labcas-metadata-and-common-data-elements/metadata-collection-form/)
