### ISSUE TITLE
Search publications by author

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#377]
## 🤔 Tell Us About the Feature

During the EDRN bio-informatics systems planning meeting on 2024-10-10, Christos wanted a way to search for publications by author; for example, on the [Publications page](https://edrn.nci.nih.gov/data-and-resources/publications/), you can't type "Skates" to see just his publications.

Also, when viewing a specific publication [such as this one](https://edrn.nci.nih.gov/data-and-resources/publications/37251695-edrnknowledgepubvia-grants37251695-a-flexible-method-for-diagnostic-accuracy-with-biomarker-measurement-error/), the author names don't link back to their investigator pages.

Lastly, when viewing a specific publication, a full publication date would be nice.

## 🎇 What Solution You'd Like

What Christos wants.

**Comment by nutjob4life** [comment]
@hoodriverheather I've assigned this to you initially to double-check against your recording that I captured everything Christos wants. Feel free to edit the tickjet description to add/remove/change details.

Once everything's copacetic, please assign back to me.

**Comment by hoodriverheather** [comment]
@nutjob4life that sounds right to me.

**Comment by nutjob4life** [comment]
@hoodriverheather this is now live on the [dev site](https://edrn-dev.jpl.nasa.gov/portal/renaissance/). To QC this:

1. Visit the [publications page](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/publications/) and notice the new column between titles and journal. Type "Skates". Those EDRN publications that the DMCC informs us as having Skates's site associated with it appears.
2. Click on a hit such as "[Ovarian cancer biomarker performance in prostate, lung, colorectal, and ovarian cancer screening trial specimens.](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/publications/21372036-3035-ovarian-cancer-biomarker-performance-in-prostate-lung-colorectal-and-ovarian-cancer-screening-trial-specimens/)". Notice on the right, there is a new section, "EDRN PI Authors". Again, this is the data provided by the DMCC that tells us that a publication is associted with three sites—which has three PIs. Click on each PI to learn more about them.
3. Lastly, look at the bottom of the right-column under "Appears In". Notice that the month now appears.

Christos wanted the full publication date; the Medline database and Entrez API only provides Year and Month, though, so adding month is the best we can do.

**Comment by hoodriverheather** [comment]
Looks great to me!

**Comment by hoodriverheather** [comment]
@nutjob4life Should these publications also show on the EDRN Person's page? I searched on Ziding in publications and saw approx 30 pages. His page doesn't show any pubs https://edrn-dev.jpl.nasa.gov/portal/renaissance/about-edrn/sites/1012-fred-hutchinson-cancer-center/feng-ziding/

**Comment by hoodriverheather** [comment]
@nutjob4life maybe that's just odd for Ziding because of the switching of DMCC PI? Other 2 that i tested seem to match. Skates and Cramer. IDK

**Comment by nutjob4life** [comment]
@hoodriverheather you may have been seeing transitional data between the movement of publications from Ziding to Yengyi. As of today, Nov 9—after another full overnight ingest—here's what I get when I put in Ziding for a search:

<img width="1012" alt="Screenshot 2024-11-09 at 8 02 39 AM" src="https://github.com/user-attachments/assets/cd88c02a-672e-4d72-863a-acf10ca801ec">

**Comment by nutjob4life** [comment]
@hoodriverheather doesn't hurt to ask

On the topic of this issue, though? Are we good to mark this as QC'd and clear to close?

**Comment by hoodriverheather** [comment]
@nutjob4life Yes!
