### ISSUE TITLE
 page-within-a-page

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#38]
## 🐛 Describe the Bug
In the biomarker tab of the portal and when I click on a biomarker name to drill into a marker, I get a portal page within a portal page. See attached screen shot.

## 📜 How To Reproduce

Cannot reproduce

❗️ Mention if the bug appears:
[X] When not logged in

or possibly *all* the time!

## 🖼 Screenshots

<img width="1334" alt="Screen Shot 2020-06-17 at 2 22 05 PM" src="https://user-images.githubusercontent.com/58526347/85075104-7ecd6700-b172-11ea-88ef-4ff22891c1ff.png">

**Comment by nutjob4life** [comment]
Possibly due to a reload with internal tabs?

**Comment by nutjob4life** [comment]
One possible reproduction:
1. Visit home, `/`, *log out* if logged in
2. Click Groups and Committees, `/groups`
3. Visit Biomarker Developmental Laboratories`/groups/biomarker-developmental-laboratories`
4. Force reload (⇧⌘R on Firefox or Chrome, ⌥ + click Reload button on Safari)

**What the heck!?** 😮 Once you do it on one browser, it's messed up on other browsers!

**Comment by hoodriverheather** [comment]
I cannot recreate. Looks good.
