### ISSUE TITLE
Unexpected search results - search w/i biomarker tab

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#39]
## 🐛 Describe the Bug

Searching on "14-3-3 theta" using the free text search box within the biomarker tab, it did not return any results
## 📜 How To Reproduce

cannot reproduce. seems to be working.
https://edrn.nci.nih.gov/biomarkers#c0=20&b_start=0&c3=14-3-3

**Comment by nutjob4life** [comment]
Fixed by the same fix to #32 — title attributes on knowledge objects weren't being searched, but now they are.

**Comment by nutjob4life** [comment]
@hoodriverheather to confirm this is now fixed, please try

1. Visit https://edrn-dev.jpl.nasa.gov/portal/5/dev/biomarkers
2. Enter `14-3-3 theta` into the "Search" box under "Indicators for cancer."
3. Confirm there are 7 matches:
- AFP
- AFP-L3
- DCP
- DCP and AFP-L3 risk biomarkers for HCC
- Hanash 3 marker panel for Lung Cancer
- SPP1
- YWHAQ

If not, go ahead and re-open the issue 💔

**Comment by hoodriverheather** [comment]
Looks great!
