### ISSUE TITLE
Link to OncoMX from Portal

### ISSUE THREAD

**Issue by yuliujpl** [EDRN/P5#66]
## 🤔 Tell Us About the Feature

Can we link cancer evidence data consolidated within OncoMX into EDRN Portal? OncoMX links the following data sources with gene names as a unified identifier across the data sources. Below are the online derived descriptions for each of the dbs:
dimex: DiMeX consists of a series of natural language processing modules that preprocess input text and apply syntactic and semantic patterns to extract mutation-disease association
dexter: Disease-Expression Relation Extraction from Text (DEXTER) to extract information from literature on gene and microRNA expression in the context of disease
fda*: This dataset lists FDA approved cancer biomarker tests are mined from web resources
bmuta: BioMuta contains nonsynonymous single-nucleotide variations (nsSNVs) found in cancer, integrated and unified from multiple resources and annotated with functional information and literature evidence.
bxpress: BioXpress is a knowledgebase containing gene and miRNA expression levels and changes reported from paired tumor and adjacent normal tissues from cancer samples
scrna: This dataset reports the specificity for gene expression level across with respect to cell type as analyzed from cancer data
bgee*: Bgee integrates and analyzes gene expression patterns from a variety of experimentally generated data types, including microarray, in situ hybridization, EST, and RNA-Seq. Only the subset of RNA-Seq data are used to generate the expression profiles for healthy individuals for human and mouse used by OncoMX

## 🎇 What Solution You'd Like

OncoMX has a search api built that lets you query by hgnc symbol. By using this api, one can pull cancer data in json back to EDRN Portal for tabular/analytical display. The API works like the following to search:
https://beta.oncomx.org/querycache?query={gene or list of genes in comma}
example:
https://beta.oncomx.org/querycache?query=FAP 
https://beta.oncomx.org/querycache?query=FAP,BRCA2

There is also a way to update the cache through the api as well (similar but dumbed down version of ingestAll function in EDRN):
https://beta.oncomx.org/regeneratecache (Takes about an hour to finish)
One can reload the cache with any of the latest updates on a monthly basis (though it might make sense for OncoMX to just run this whenever the database is updated, should be automate in an intelligent way as a future release).

**Comment by nutjob4life** [comment]
Closing this as apparently it's never been needed.
