### ISSUE TITLE
Separate Bug Fix, LabCAS-ingest, and New Look/Menu Release

### ISSUE THREAD

**Issue by nutjob4life** [EDRN/P5#72]
## 🤔 Tell Us About the Feature

- Let's get Plone 5.2 bug fixes, protocol view stack traces, etc., shipped out to NCI ASAP as a bug fix release.
- See how Science Data ingest from LabCAS works and demo this on edrn.jpl.nasa.gov
- Postpone all the new look/feel to the _next_ release

## 🗺 Context

Decided during Informatics Center status meeting, 2020-09-22.

**Comment by nutjob4life** [comment]
OK, https://edrn-dev.jpl.nasa.gov/portal/5/dev/ is updated software-wise.

LabCAS 2.0 RDF though is wonky. It's given 4036 datasets (compared with LabCAS 1.0's 78). I will need David & Luca's help to figure out what's going on with that.

**Comment by nutjob4life** [comment]
Ingest complete, @hoodriverheather, @dcrichto:

OK so https://edrn-dev.jpl.nasa.gov/portal/5/dev/ has only bug fixes, stability fixes, and performance upgrades for the Portal and not the new menus or content organization. Note that a few of Kara's Section 508 issues also snuck into this release from #69 but that's probably okay.

The "Data" tab is a problem; may want to go back to eCAS ingest instead of LabCAS ingest:

- LabCAS RDF I have points to the old LabCAS 1.0 UI
- I tried updating [edrn.rdf](https://github.com/EDRN/edrn.rdf) to use LabCAS 2.0 but for some reason I get over ~4000 datasets instead of just ~80. I'm hoping @yuliujpl or @LucaCinquini can help figure that out!

Please review the dev site and let me know how you'd like to proceed.

**Comment by hoodriverheather** [comment]
Hi Sean,
I think we really need the data to update from LabCAS 2.0. All new data is only going into LabCAS. We’ve also been doing a lot of data cleanup in LabCAS, that might be the increase in datasets. Not sure about ~4000.
In reviewing dev site I noticed:

  *   the plone logo in left upper header. Is this just a place holder?
  *   The protocols now seem to be working, but if a protocol has data in LabCAS – there is no link (see attached screen shot)

The protocol bug fix seems to be working. Can you remind me of any other fixes I should test specifically in this release?
Thanks,
Heather

**Comment by nutjob4life** [comment]
This is fixed.
