### ISSUE TITLE
Missing/broken links EDRN portal revamp

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#96]
## 🐛 Describe the Bug
This page does not exist:
From - Application Procedure, Receipt Dates, and Review (https://edrn-dev.jpl.nasa.gov/portal/5/dev/archive/colops/aprdr), click contact EDRN Principal Investigator - https://edrn-dev.jpl.nasa.gov/portal/5/dev/archive/sites. See screenshot.
<img width="1412" alt="Screen Shot 2021-01-11 at 7 59 42 PM" src="https://user-images.githubusercontent.com/58526347/104267984-b02bbe00-5447-11eb-85b8-0f0f6c148a43.png">

From - Work with EDRN -> Advocacy Groups (https://edrn-dev.jpl.nasa.gov/portal/5/dev/work-with-edrn/advocacy-groups) ->Webinars (Presentations and Handouts) - page does not exist.
<img width="1337" alt="Screen Shot 2021-01-11 at 8 22 25 PM" src="https://user-images.githubusercontent.com/58526347/104269265-bf603b00-544a-11eb-97a3-75c896af3fdc.png">

From - Work with EDRN -> Advocacy Groups (https://edrn-dev.jpl.nasa.gov/portal/5/dev/work-with-edrn/advocacy-groups) -> Video unavailable.
<img width="1246" alt="Screen Shot 2021-01-11 at 8 23 21 PM" src="https://user-images.githubusercontent.com/58526347/104269352-f2a2ca00-544a-11eb-8c40-adfc73fcda04.png">

**Comment by nutjob4life** [comment]
Fixed:

1. Page was in the `/archive` section of the portal. There's a new page to hold it now and has the correct link.
2. Advocacy goes to new webinars location.
3. Video got removed from YouTube so removed video from page.
