### ISSUE TITLE
The home page - Work with EDRN doesn't match the Work with EDRN page

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#97]
The home page has link to Find/Participate in a Collaborative Study - https://edrn-dev.jpl.nasa.gov/portal/5/dev/archive/colops
<img width="1222" alt="Screen Shot 2021-01-11 at 8 28 43 PM" src="https://user-images.githubusercontent.com/58526347/104269855-19153500-544c-11eb-8993-b2166539c3c3.png">

The Work with EDRN page - https://edrn-dev.jpl.nasa.gov/portal/5/dev/work-with-edrn and the drop down menu has find a sponsor. 
<img width="1258" alt="Screen Shot 2021-01-11 at 8 28 26 PM" src="https://user-images.githubusercontent.com/58526347/104270001-5e396700-544c-11eb-88ec-120d78e4f648.png">

Not sure which is right or if they are supposed to match.

**Comment by nutjob4life** [comment]
I'll pick one.

**Comment by nutjob4life** [comment]
Fixed; the terminology is "Find a Sponsor" in all three places and all go to the same place on the DMCC site.

**Comment by hoodriverheather** [comment]
Hi Sean,
I'm not sure these are all the same. This page - https://edrn.jpl.nasa.gov/portal/archive/colops still seems relevant and is not the find a sponsor page. Do we have a link to it somewhere in this new structure?

**Comment by nutjob4life** [comment]
Well it's in the archive so it's not going away. We can always change things _after we release 5.1.0_.
